Improve folder watcher
nextcloud/desktop pull request #2538
Opened 2020-10-09 16:55 UTC by camilasan

2020-10-19 14:30 UTC, camilasan commented
/rebase

2020-10-19 16:38 UTC, er-vin requested changes
First commit in that series probably shouldn't be cherry-picked. It is already in our history and I think it led to some conflicts (or missing conflicts) handling which made some of the resulting commits on top further away from the original than necessary (one even ended up empty and that one probably shouldn't).

This needs to be reworked a bit.

2020-10-19 16:38 UTC, er-vin commented on src/gui/folderwatcher_win.cpp
> +                qCWarning(lcFolderWatcher) << "The target file system does not support ReadDirectoryChangesW, the function fails with ERROR_INVALID_FUNCTION" << errorCode;
Putting errorCode here is redundant I'd say, we know its value.

2020-11-23 20:07 UTC, camilasan commented
#2660

2020-11-23 20:07 UTC, closed without merging