Fix macOS bug where tray window causes spaces to switch
nextcloud/desktop pull request #2677
Opened 2020-11-30 18:18 UTC by briankendall

Closes #2332 

Let me know if there's any changes you need to the PR and I'll be happy to update my commit

2020-12-01 05:53 UTC, er-vin commented
/rebase

2020-12-01 05:57 UTC, er-vin requested changes

2020-12-01 05:57 UTC, er-vin commented on src/gui/systray.h
> +void setTrayWindowLevelAndVisibleOnAllSpaces(QQuickWindow *qtWindow);
I'd rename the parameter from qtWindow to window. Also seeing how it's used please change the type to QWindow.

2020-12-01 05:57 UTC, er-vin commented on src/gui/systray.mm
> +#include <QQuickWindow>
Please include QWindow instead.

2020-12-01 05:57 UTC, er-vin commented on src/gui/systray.mm
> +void setTrayWindowLevelAndVisibleOnAllSpaces(QQuickWindow *qtWindow)
Rename the parameter and change its type please.

2020-12-01 05:57 UTC, er-vin commented on src/gui/systray.mm
> +    NSPanel *window = (NSPanel *)[view window];
Please change window here to nativeWindow.

2020-12-01 16:51 UTC, briankendall commented
Okay I made the requested changes. (And fixed my usage of `NSPanel` instead of `NSWindow` which wasn't technically correct.) Let me know if there's anything else you'd like me to do.

2020-12-02 06:53 UTC, er-vin commented
/rebase

2020-12-02 07:23 UTC, er-vin approved these changes

2020-12-02 07:23 UTC, merged