Improve Inotify cmake code
nextcloud/desktop pull request #3059
Opened 2021-04-01 19:11 UTC by nicolasfella

Use the FindInotify from ECM. It handles the case of Linux vs BSD
correctly automatically.

Also only find Inotify on Linux and BSD

Signed-off-by: Nicolas Fella <nicolas.fella@gmx.de>

2021-04-01 19:39 UTC, FlexW commented
There is already https://github.com/nextcloud/desktop/pull/2886 that does the same.

2021-04-12 09:51 UTC, mgallien commented
/rebase

2021-04-12 09:53 UTC, mgallien approved these changes
Thanks @nicolasfella

2021-04-12 09:57 UTC, FlexW commented
@mgallien @nicolasfella We had today a bug report that CMake tries to link libraries twice. This is caused by not using the `PUBLIC` keyword on `target_link_libraries`. I created a draft pr to resolve that issue and wait for feedback if it works. Maybe it would be a good idea to incorporate the changes from my draft pr into this pr, so that compilation actually works on free bsd.

Thats the issue: https://github.com/nextcloud/desktop/issues/3080

That is my draft pr: https://github.com/nextcloud/desktop/pull/3084

2021-04-12 15:10 UTC, FlexW commented
@nicolasfella After some investigation by @mgallien, we are now sure that we need the PUBLIC keyword there. At the moment it's not clear why this is needed and PRIVATE is not enough, but we can postpone the investigation. 

Would be great if you can add the PUBLIC keywords, like I did in my draft pr, to this pr. Then we can merge it.

2021-04-12 15:11 UTC, FlexW requested changes

2021-04-12 15:11 UTC, FlexW commented on src/libsync/CMakeLists.txt
> +    target_link_libraries(${synclib_NAME} ${Inotify_LIBRARIES})
Please add the PUBLIC specifier

2021-04-12 15:14 UTC, nicolasfella commented
> @nicolasfella After some investigation by @mgallien, we are now sure that we need the PUBLIC keyword there. At the moment it's not clear why this is needed and PRIVATE is not enough, but we can postpone the investigation.
> 
> Would be great if you can add the PUBLIC keywords, like I did in my draft pr, to this pr. Then we can merge it.

Done

2021-04-12 15:59 UTC, mgallien approved these changes
Thanks

2021-04-13 06:35 UTC, FlexW approved these changes

2021-04-13 06:35 UTC, FlexW commented
/rebase

2021-04-13 06:46 UTC, merged

2021-04-13 08:00 UTC, er-vin commented
Note that PUBLIC and PRIVATE uses for target_link_libraries is something which needs to be more widely done in the project. Again to file into the "buildsystem needs a big cleanup" department. :-)