Replace deprecated endl with &Qt::endl
nextcloud/desktop pull request #3130
Opened 2021-04-14 16:00 UTC by elsiehupp

I also replaced `std::endl` with `&Qt::endl` for good measure.

This compiles correctly on macOS (#3124 aside).

Resolves the following compiler warnings:
```
//src/libsync/logger.cpp:139:37: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
            (*_logstream) << msg << endl;
                                    ^
//src/libsync/theme.cpp:698:28: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
           << version() << endl;
                           ^
//src/libsync/theme.cpp:700:46: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
    stream << "Git revision " << GIT_SHA1 << endl;
                                             ^
//src/libsync/theme.cpp:702:87: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...Qt " << qVersion() << ", built against Qt " << QT_VERSION_STR << endl;
                                                                      ^
//src/libsync/theme.cpp:705:93: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...Qt platform plugin '" << QGuiApplication::platformName() << "'" << endl;
                                                                        ^
//src/libsync/theme.cpp:707:76: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
    stream << "Using '" << QSslSocket::sslLibraryVersionString() << "'" << endl;
                                                                           ^
//src/libsync/theme.cpp:708:105: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...<< ", " << QSysInfo::currentCpuArchitecture() << endl;
                                                      ^
//src/libsync/theme.cpp:702:87: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...Qt " << qVersion() << ", built against Qt " << QT_VERSION_STR << endl;
                                                                      ^
//src/libsync/theme.cpp:705:93: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...Qt platform plugin '" << QGuiApplication::platformName() << "'" << endl;
                                                                        ^
//src/libsync/theme.cpp:707:76: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
    stream << "Using '" << QSslSocket::sslLibraryVersionString() << "'" << endl;
                                                                           ^
//src/libsync/theme.cpp:708:105: warning: 
      'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
  ...<< ", " << QSysInfo::currentCpuArchitecture() << endl;
                                                      ^
```

2021-04-14 16:10 UTC, nicolasfella commented
Note that Qt::endl requires Qt 5.14 while the currently stated requirement in CMake is 5.12. The CI also builds with 5.12

2021-04-17 22:33 UTC, elsiehupp commented
It turned out that removing `endl` without relying on `Qt::endl` was slightly more complicated, but apparently not impossible. I’m not sure what behaviors to double-check with these changes, though. Is it all just logging stuff?

2021-04-17 22:50 UTC, nicolasfella commented
`endl`/`Qt::endl` does two things: It writes a line break ("\n") and flushes the stream. flush forces all pending changes to be written out to the disk or output.

In likely most of the cases we are interested in the line break and not really in the flush. For example in https://github.com/nextcloud/desktop/pull/3130/files#diff-a5ddfae24f1c85490bfa7366eef81d9bee905a0f8fec7bf94edff0fc04eae93dL83 we need the line breaks, otherwise the resulting file is ill-formed.

We have a couple of options now:
1) we do nothing. There's nothing technically wrong with endl, the Qt folks just want to move it into a namespace. It only becomes problematic once we want to move to Qt6. Once we require Qt 5.15 we can address this.
2) We replace endl with "\n" where we are not interested in the flush and manually use flush where needed
3) We use ifdef or typedefs to conditionally use endl vs Qt::endl depending on the Qt version we build against

2021-04-21 07:29 UTC, er-vin commented
Honestly I'd lean toward option (1). :-)

This kind of things are better addressed at the latest moment before a major version bump, so would be addressed during a Qt 5.15 period.

2021-05-02 15:45 UTC, elsiehupp commented
> This kind of things are better addressed at the latest moment before a major version bump, so would be addressed during a Qt 5.15 period.

I should have mentioned this earlier, but my intention in addressing these various compiler warnings was to facilitate a version bump. I just didn’t know that the CI was running 5.12 rather than 5.15.

The reason I’m antsy to pursue a version bump is among other things Issue https://github.com/nextcloud/desktop/issues/2584, which doesn’t seem like it will be resolved with the current version of Qt.

2021-05-14 12:43 UTC, mgallien commented
> `endl`/`Qt::endl` does two things: It writes a line break ("\n") and flushes the stream. flush forces all pending changes to be written out to the disk or output.
> 
> In likely most of the cases we are interested in the line break and not really in the flush. For example in https://github.com/nextcloud/desktop/pull/3130/files#diff-a5ddfae24f1c85490bfa7366eef81d9bee905a0f8fec7bf94edff0fc04eae93dL83 we need the line breaks, otherwise the resulting file is ill-formed.
> 
> We have a couple of options now:
> 
>     1. we do nothing. There's nothing technically wrong with endl, the Qt folks just want to move it into a namespace. It only becomes problematic once we want to move to Qt6. Once we require Qt 5.15 we can address this.
> 
>     2. We replace endl with "\n" where we are not interested in the flush and manually use flush where needed
> 
>     3. We use ifdef or typedefs to conditionally use endl vs Qt::endl depending on the Qt version we build against

I do not want to change that now as this is just distracting us from the move to Qt 5.15 for something that we will be able to solve at that time.

2021-05-14 12:45 UTC, mgallien requested changes
I do not understand the current state of this PR. you have replaced `std::endl` by using `flush` and that is not equivalent.
are you sure that is what you want ?

2021-05-14 15:24 UTC, elsiehupp commented
The state of this PR is that you should ignore it for the time being because I forgot about it. I’ll mark it as a draft.

2021-09-03 20:32 UTC, FlexW commented
Superseded by https://github.com/nextcloud/desktop/pull/3747

2021-09-03 20:32 UTC, closed without merging

2021-09-05 15:05 UTC, elsiehupp commented
I never finished working on this because it seemed like it was premature (i.e. the problem was I was using a different version of Qt than the CI pipeline was). But… it seems like you got around to

2021-09-05 15:05 UTC, elsiehupp commented
I never finished working on this because it seemed like it was premature (i.e. the problem was I was using a different version of Qt than the CI pipeline was). But… it seems like you got around to the project of updating to the next major version of Qt.

2021-09-06 08:23 UTC, mgallien commented
@elsiehupp You are still very much welcome to help us fix all deprecation warnings
Now that we require Qt 5.15 that should be easier