clang's variadic macro warnings: only for clang
nextcloud/desktop pull request #3132
Opened 2021-04-14 20:21 UTC by yopito

following settings of cmake/modules/Warnings.cmake

once applied, no more zillon of warning on building as below:
```
cc1plus: note: unrecognized command-line option '-Wno-gnu-zero-variadic-macro-arguments' may have been intended to silence earlier diagnostics
```

2021-04-15 14:10 UTC, FlexW commented
Thanks. Could you do it in a little bit different way, so that the flags get not set globally. Paste this
```CMake
# Calling Qt's qCWarning(category, ...) with no params for "..." is a GNU
# extension (C++11 §16.3/4 forbids them). Silence clang's warnings.
target_compile_options("${csync_NAME}" PUBLIC
  $<$<CXX_COMPILER_ID:Clang>:-Wno-gnu-zero-variadic-macro-arguments>
  $<$<C_COMPILER_ID:Clang>:-Wno-gnu-zero-variadic-macro-arguments>)
```
right below `add_library("${csync_NAME}" ...)` in `src/csync/CMakeLists.txt`.

Then remove
```CMake
  # Calling Qt's qCWarning(category, ...) with no params for "..." is a GNU
  # extension (C++11 §16.3/4 forbids them). Silence clang's warnings.
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-gnu-zero-variadic-macro-arguments")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-gnu-zero-variadic-macro-arguments")
```
entirely from `src/CMakeLists.txt`

2021-04-15 14:11 UTC, FlexW requested changes

2021-04-15 14:11 UTC, FlexW commented on src/CMakeLists.txt
> +  endif()
See my comment

2021-04-15 21:21 UTC, yopito commented
hello @FlexW : thanks for your inputs.  
I don't feel confident to apply your changes: I don't understand them, not fluent enough in cmake.  
Would you patch it on you own (PR) ?

2021-04-16 07:37 UTC, FlexW commented
@yopito Yes, I can do it. But thinking a bit more about this, I'm not sure anymore if that is the best way to solve the problem. I have the feeling that setting this warning should be a private property and not automatically should change the flags on all targets that link to the csync target. However, if making it private, we need to set it on each target separate. @mgallien What do you think?

2021-04-21 07:18 UTC, er-vin commented
By the way, would that be more appropriate to do that in master and backport? So far the project followed a backport strategy not a forward port one.

2021-04-22 10:52 UTC, FlexW commented
> By the way, would that be more appropriate to do that in master and backport? So far the project followed a backport strategy not a forward port one.

Of course that would be better :) Thanks for hinting it.

2021-04-23 22:15 UTC, yopito commented
OK, I've reworked this PR against master branch.
Have to "signoff commit to please the DCO bot"

2021-04-26 12:51 UTC, FlexW approved these changes
Thank you. I'll will merge that now as it is.

2021-04-26 13:21 UTC, FlexW commented
/rebase

2021-04-26 14:02 UTC, merged