use folders in CMake
nextcloud/desktop pull request #3286
Opened 2021-05-07 12:17 UTC by Dimon4eg

This sets folders for targets to be visible in an IDE.

Before in VS (if tests ore on):
![NC_3 2](https://user-images.githubusercontent.com/1271541/117448121-02d53c80-af47-11eb-8598-c713d12372d7.png)

Now in VS:
![NC_3 2_folders](https://user-images.githubusercontent.com/1271541/117448136-0799f080-af47-11eb-8b7b-bae2d3cb90c4.png)

2021-05-07 13:31 UTC, mgallien requested changes
Thanks, nice idea
Please address my comment and we should good to go

2021-05-07 13:31 UTC, mgallien commented on CMakeLists.txt
> +set_property(GLOBAL PROPERTY USE_FOLDERS ON)
Please could you add it to `cmake/modules/DefineCMakeDefaults.cmake` ?

2021-05-14 08:49 UTC, Dimon4eg commented
@mgallien take a look again plz

2021-05-14 12:48 UTC, mgallien commented
/rebase

2021-05-14 12:50 UTC, mgallien commented
Thanks
Please do not merge master when working on a PR but rebase on top of master. We will always rebase before merging a PR and the history should not include merge like this one. I have to write some documentation about that to make contributing easier.

2021-05-14 12:51 UTC, mgallien approved these changes

2021-05-14 12:53 UTC, Dimon4eg commented
I see, I just pressed button `Update branch` in this PR

2021-05-17 06:31 UTC, allexzander commented
> I see, I just pressed button `Update branch` in this PR

No worries. For the future, you will need to add a comment:

/rebase

in the PR. This will do the trick.

2021-05-17 06:43 UTC, allexzander approved these changes

2021-05-17 23:54 UTC, Dimon4eg commented
`use folders for nextcloudsync source files` commit makes this:

![image](https://user-images.githubusercontent.com/1271541/118570171-3fddd200-b784-11eb-9519-2b221f224bbc.png)

2021-05-18 00:44 UTC, Dimon4eg commented
`use folders for nextcloudCore source files` commit makes this:

![image](https://user-images.githubusercontent.com/1271541/118573439-3c9a1480-b78b-11eb-9d69-699348c10856.png)

2021-05-18 06:46 UTC, mgallien requested changes
Please next time, once a PR is approved do not push more changes to it. That is not fair for the reviewers.

Please remove your new changes and push them to another PR. It would be nice if we can merge your first one.

2021-05-18 07:05 UTC, Dimon4eg commented
Ok, sorry, no problem

2021-05-18 10:16 UTC, mgallien approved these changes

2021-05-18 10:17 UTC, merged