Add systemd user service
nextcloud/desktop pull request #3510
Opened 2021-07-03 20:06 UTC by Tachi107

Closes #728 

I didn't know where to put the systemd unit, so I created a `systemd/` directory. Let me know if there is a more appropriate place :)

2021-07-12 14:50 UTC, FlexW commented
I just wanted to throw in that this might not play nice with the autostart file that we provide. If the user disables autostart in the application, and has the systemd file installed, the settings from the gui get not respected anymore. That may confuse users.

2021-07-12 15:17 UTC, Tachi107 commented
> I just wanted to throw in that this might not play nice with the autostart file that we provide. If the user disables autostart in the application, and has the systemd file installed, the settings from the gui get not respected anymore. That may confuse users.

I agree, the UI is completely unaware of the systemd unit, but it is also true that having the unit installed does not cause the service to start, so unless the user manually runs `systemctl --user enable nextcloud-desktop` nothing strange should happen.

Syncing the UI and the systemd unit would be nice though

2021-07-12 15:30 UTC, Tachi107 commented
I just noticed that running Nextcloud through systemd causes some minor issues; the client does not respect GTK settings like icon theme, font, etc (see screenshot).

Nothing that would cause serious problems, but I would prefer to first fix that issues and then let you merge this. Sorry for not noticing earlier :) (this also says a lot about the severity of the issue)

![image](https://user-images.githubusercontent.com/34214253/125314650-ad4a5100-e336-11eb-9e79-37ebf83d8831.png)

![image](https://user-images.githubusercontent.com/34214253/125314751-c4893e80-e336-11eb-8934-fd2d4685c7bb.png)

2021-07-12 17:45 UTC, Tachi107 commented
This looks like a Qt issue, as running GTK apps through systemd does not cause any issue, while apps like qbittorrent suffer from the same problem. 

If anyone has any suggestion it would be much appreciated :)

2021-07-15 10:17 UTC, mgallien commented
> This looks like a Qt issue, as running GTK apps through systemd does not cause any issue, while apps like qbittorrent suffer from the same problem.
> 
> If anyone has any suggestion it would be much appreciated :)

I guess you will want to modify `Wants=network-online.target` to be launched once the desktop environment is launched such that env variables are set and allow getting the proper style
one guess it to use `graphical-session.target` but I am not sure

2021-07-15 13:19 UTC, Tachi107 commented
> I guess you will want to modify Wants=network-online.target to be launched once the desktop environment is launched such that env variables are set and allow getting the proper style 

That's the same thing I thought, but it seems that it doesn't solve the issue. Even manually restarting the service after the system is fully booted does nothing.

2021-07-16 13:10 UTC, mgallien commented
> > I guess you will want to modify Wants=network-online.target to be launched once the desktop environment is launched such that env variables are set and allow getting the proper style
> 
> That's the same thing I thought, but it seems that it doesn't solve the issue. Even manually restarting the service after the system is fully booted does nothing.

I will have another look soon unless somebody is faster than me

2021-12-18 16:27 UTC, lars-becker commented
If I remember correctly KDE has a daemon running for managing icons and the like. Might be handled by kded, but this is only a wild guess.

2022-06-22 09:28 UTC, mgallien commented
@Tachi107 I am really sorry for the lack of followup from me on this one
going to test it and see if I can get it merged

2022-06-22 09:31 UTC, Tachi107 commented
Don't worry :)
I've been using this for quite a while now, and apart from the minor issues I mentioned before I did not encounter any other problems

2023-06-21 05:34 UTC, claucambra approved these changes

2023-07-04 08:35 UTC, mgallien requested changes

2023-07-04 08:35 UTC, mgallien commented on systemd/nextcloud-desktop.service.in
> +ExecStart=@bindir@/nextcloud --background
executable name is defined as a variable in cmake files
please replace this by this variable `APPLICATION_EXECUTABLE`

2023-07-04 09:03 UTC, mgallien requested changes
see my other comments
for the context
when developing the Nextcloud client, I run in parallel the latest official AppImage binary
so to be able to run my self built desktop client, I make changes to `NEXTCLOUD.cmake` to not conflict with the already running client

2023-07-04 09:03 UTC, mgallien commented on systemd/nextcloud-desktop.service.in
> +Description=Nextcloud desktop user service
please replace `Nextcloud` by this variable from cmake `APPLICATION_NAME`

2025-02-13 08:17 UTC, mgallien commented
@Tachi107 gentle ping
could you have a look at the requested changes ?
without a reply from you I would take over the PR and create a branch cherry-picking your commit
in any case, thanks for the contribution

2025-02-13 10:37 UTC, Tachi107 commented
Oh yeah, sure, don't be afraid to ping. I most likely forgot about this. I'll take a look later today :) 

Il 13 febbraio 2025 09:17:53 CET, Matthieu Gallien ***@***.***> ha scritto:
>mgallien left a comment (nextcloud/desktop#3510)
>
>@Tachi107 gentle ping
>could you have a look at the requested changes ?
>without a reply from you I would take over the PR and create a branch cherry-picking your commit
>in any case, thanks for the contribution
>

2025-02-14 08:33 UTC, thomasmerz commented
Just as a hint… maybe you might want to have a look at how [Syncthing](https://github.com/search?q=repo%3Asyncthing%2Fsyncthing%20systemd&type=code) is dealing this!?
```
$ systemctl status syncthing*|ack Synct
● syncthing@user1.service - Syncthing - Open Source Continuous File Synchronization for user1
● syncthing@user2.service - Syncthing - Open Source Continuous File Synchronization for user2
```

2025-03-14 13:58 UTC, mgallien commented
there is no need to have multiple instances of the same service to run the client as only one instance of the client can run at a time (enforced by a runtime check in the code)
@Tachi107 do you still plan to do the requested changes ? (replacing some text by variables ?)

2025-03-15 19:13 UTC, Tachi107 commented
On Fri Mar 14, 2025 at 2:58 PM CET, Matthieu Gallien wrote:
> @Tachi107 do you still plan to do the requested changes ? (replacing 
> some text by variables ?)

Done! I've also changed the code to discover the systemd user unit 
directory using the systemd.pc pkg-config file.

2025-03-25 14:22 UTC, merged

2025-05-08 13:39 UTC, thomasmerz commented
@claucambra when or in which package (openSUSE) will this systemd-service-unit per user be available?