Add documentation for user status selector dialog
nextcloud/desktop pull request #3779
Opened 2021-09-10 13:29 UTC by FlexW

Fixes #3770

Signed-off-by: Felix Weilbach <felix.weilbach@nextcloud.com>

2021-09-13 14:09 UTC, mgallien commented on doc/navigating.rst
> +If you have the user status app is installed on your Nextcloud server,
you have an extra `is`
```
If you have the user status app installed on your Nextcloud server,
```

2021-09-13 14:09 UTC, mgallien commented on doc/navigating.rst
> +dots. In the menu that now opened click on **Set status**.
better
```
dots. In the menu that opens click on **Set status**.
```

2021-09-13 14:09 UTC, mgallien commented on doc/navigating.rst
> +In the dialog that will now open, you can set your online status if
remove future usage
```
In the dialog that opens, you can set your online status if
```

2021-09-13 15:10 UTC, FlexW commented
/rebase

2021-09-14 07:25 UTC, FlexW commented
/rebase

2021-09-14 12:54 UTC, mgallien commented on doc/navigating.rst
> +the main dialog. Then click on your avatar and then click on the tree
s/tree/three/

2021-09-14 12:56 UTC, mgallien requested changes
just a small last typo

2021-09-16 08:35 UTC, FlexW commented on doc/navigating.rst
> +the main dialog. Then click on your avatar and then click on the tree
thanks. done

2021-09-16 10:16 UTC, mgallien commented on doc/navigating.rst
> +the main dialog. Then click on your avatar and then click on the tree
in the last commit it is still `tree`

2021-09-16 10:32 UTC, FlexW commented on doc/navigating.rst
> +the main dialog. Then click on your avatar and then click on the tree
I forgot to push. Sorry.

2021-09-17 07:21 UTC, mgallien approved these changes

2021-09-17 07:24 UTC, allexzander approved these changes

2021-09-17 08:21 UTC, mgallien commented
/rebase

2021-09-17 09:05 UTC, merged