Write logs to local, not config dir
nextcloud/desktop pull request #3868
Opened 2021-10-04 12:00 UTC by franga2000

As discussed in #3406

Tested:

- Platforms:
  - [x] Linux
  - [ ] Windows
  - [ ] Mac OS
 - Features:
   - [x] Dir structure and files created and written to as normal
   - [x] Old logs are gzipped correctly
   - [x] Creating a debug archive still includes log files

2021-10-04 12:40 UTC, FlexW commented
Cool, thank you :) will you be able to test it on Windows and macOS aswell?

2021-10-04 12:58 UTC, franga2000 commented
Yes, but I'm still setting up toolchains on both. Should have results in a few hrs

2021-10-05 06:31 UTC, allexzander requested changes

2021-10-05 06:31 UTC, allexzander commented on src/libsync/configfile.cpp
> +    const auto defaultLogDir = QString(QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation) + QStringLiteral("/logs"));
@franga2000 I'd say, you need to change the corresponding part in `QString ConfigFile::configPath() const` if you want to only affect Linux. There is certain logic in `QString ConfigFile::configPath() const` that gets executed for Windows. Better try not to change the behavior.

2021-10-05 06:33 UTC, allexzander commented on src/libsync/configfile.cpp
> +    const auto defaultLogDir = QString(QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation) + QStringLiteral("/logs"));
@franga2000 Also, make sure **debug logs archive** can be generated via **Settings** dialog UI after this change.

2021-10-29 19:58 UTC, franga2000 commented
I haven't been able to build this to test on Windows or macOS as I only have VMs of them and everything takes ages to install. Any chance someone with a working build environment could give this a quick test (or at least compile and send it to me)?

2024-12-03 09:17 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-03 09:17 UTC, closed without merging