CMake: use ccache and sccache for compiler caching
nextcloud/desktop pull request #3947
Opened 2021-11-03 01:01 UTC by Be-ing

First build on Fedora 35 with an Intel Core i7 8550U: 4.5 minutes

Repeat build with ccache after deleting CMake build directory
and creating a new one: 1.5 minutes

This code is adapted from Tenacity, written by myself and
@emabrey.

ccache is easily available from Linux distribution packages and
Homebrew on macOS. sccache is the only currently maintained
compiler cache for MSVC and can be installed easily from
Chocolatey on Windows.

Signed-off-by: Be <be@mixxx.org>

2021-11-03 14:54 UTC, FlexW commented
Nice :) thank you. I haven't tested it yet, but do you think it would be possible to extract the logic into a `ccache.cmake` file (or similar) and put this file into the module folder? Would help with the readability.

2021-11-03 14:57 UTC, Be-ing commented
Yes, good idea.

2021-11-03 16:14 UTC, Be-ing commented
I refactored it to not even check for ccache if CMake is using MSVC as the compiler. Extracting this to a CMake module is a good idea. This could be easily dropped into any CMake project now.

2021-11-03 16:19 UTC, Be-ing commented
The next step after this could be using this on CI. I haven't worked with Drone before but I suppose it shouldn't be too hard. I don't see how macOS and Windows builds are done though... is CI only running for Linux?

2021-11-04 14:14 UTC, FlexW commented
> The next step after this could be using this on CI. I haven't worked with Drone before but I suppose it shouldn't be too hard. I don't see how macOS builds are done though... is CI only running for Linux and Windows?

Yes, correct. CI is only running on Windows and Linux.

2021-11-05 08:53 UTC, mgallien reviewed
thanks for the contribution
I believe I would still prefer to have this as an option that would be enabled manually
my question is because I believe some people might have `ccache` installed but would not necessarily want to use it
or is there absolutely no downside to use it ? (disc space usage, ...)

2021-11-05 13:59 UTC, Be-ing commented
> my question is because I believe some people might have ccache installed but would not necessarily want to use it

Why? I have never seen anyone raise concern about this. If they are bothered by this, they could uninstall ccache, or manually specify `-D CCACHE=OFF`.

>  or is there absolutely no downside to use it ? (disc space usage, ...)

The only downside is storage space used. The maximum cache size can be set with `ccache -M`. The default size limit is 5 GB.

2021-11-05 17:33 UTC, mgallien commented
> > my question is because I believe some people might have ccache installed but would not necessarily want to use it
> 
> Why? I have never seen anyone raise concern about this. If they are bothered by this, they could uninstall ccache, or manually specify `-D CCACHE=OFF`. FWIW Meson uses ccache by default.

How do you make sure that in no case you can get obsolete compilation products being used ?
I have bad memories of such tools that would often fail (OK, not `ccache` but still).
I am genuinely curious about `ccache` as I rarely used it in the past.

> > or is there absolutely no downside to use it ? (disc space usage, ...)
> 
> The only downside is storage space used. The maximum cache size can be set with `ccache -M`. The default size limit is 5 GB.

should not be a problem for people familiar with it

2021-11-05 17:35 UTC, Be-ing commented
> How do you make sure that in no case you can get obsolete compilation products being used ?

This is ccache's job and it does a really good job of it. I have never once had a problem that was fixed by disabling ccache.

2021-11-08 23:31 UTC, Be-ing commented
Is there anything left to do here?

2021-11-12 15:02 UTC, mgallien commented
> Is there anything left to do here?

we are in the process of pushing a release and master is frozen
we are going to have to wait
sorry

2022-01-11 13:25 UTC, mgallien commented
@Be-ing sorry for almost forgetting about this
can you rebase ?

2022-01-11 22:52 UTC, eli-schwartz commented
FWIW, while I've never had a problem caused by ccache doing bad caches that caused the wrong results, there are definitely times I didn't want to use ccache even when it is installed. Both because of the space, and because ccache is, by design, a bit slower than running the compiler on its own -- due to the file copying it kind of has to be. So, one might want to disable ccache if it is known that the build itself is a one-off build of something and the work will never be reused.

meson enables it by default, which generally works quite well, but only if you let it autodetect the compiler. You can specify `CC=gcc` to avoid autodetection, or `CC=/path/to/ccache gcc` to manually force ccache on together with the chosen compiler.

Apparently cmake defines a special option for a compiler wrapper? Interesting. Anyway, offering a cmake option to disable ccache is all that I think is needed, and that is done here... now the trick is to let people know that such an option exists without first running cmake, having it detect ccache, and then running `cmake -LH` and rapidly eyeballing the long list of internal state variables until you find ones that look like they toggle options. That problem might be unfixable, though. :D

2022-01-12 01:47 UTC, Be-ing commented
This CMake module creates `CCACHE` and `SCCACHE` boolean CMake options to manually disable compiler caching is desired.

2022-01-20 14:09 UTC, mgallien requested changes
sorry completely overlooked one thing during review (and sorry again for the delays, it is extremely busy here)
could you change the license of the new file to match existing ones (BSD 3 clauses as far as I can tell) ?
this is what is being done most of the time with cmake module files

2022-01-20 14:54 UTC, Be-ing commented
I don't mind, but this includes code originally written by @emabrey so she would need to approve relicensing it as well.

2022-02-07 17:27 UTC, camilasan commented
> I don't mind, but this includes code originally written by @emabrey so she would need to approve relicensing it as well.

Hi @emabrey, would you be ok with relicensing it as well?

2022-02-08 07:59 UTC, emabrey commented
> > I don't mind, but this includes code originally written by @emabrey so she would need to approve relicensing it as well.
> 
> Hi @emabrey, would you be ok with relicensing it as well?

Yes I'm okay with a re-license under BSD 3

2022-03-09 22:31 UTC, Be-ing commented
I just noticed that I had not updated the SPDX license identifier when copying this module to [another repo](https://github.com/KDAB/cxx-qt/pull/107). I just fixed that.

2022-03-24 11:21 UTC, claucambra approved these changes

2022-05-11 10:49 UTC, camilasan commented
/rebase

2024-12-03 09:17 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-03 09:17 UTC, closed without merging