Display error message when creating a link share with compromised password.
nextcloud/desktop pull request #4137
Opened 2022-01-05 10:16 UTC by allexzander

Signed-off-by: alex-z <blackslayer4@gmail.com>

2022-01-05 12:19 UTC, claucambra approved these changes

2022-01-05 12:38 UTC, camilasan commented
I think we need to involve @jancborchardt :)

2022-01-05 12:40 UTC, camilasan commented on src/gui/passwordinputdialog.cpp
> +QString PasswordInputDialog::password() const
new line before password()?

2022-01-05 12:48 UTC, jancborchardt commented
Looks ok for this one, but maybe it’s a bit nicer to read if we don’t use red color for the text but rather our grey/maxcontrast color: https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#text-color

2022-01-05 13:25 UTC, allexzander commented
/backport to stable-3.4

2022-01-05 14:21 UTC, allexzander commented
> maxcontrast

@jancborchardt 
![image](https://user-images.githubusercontent.com/12224014/148232859-3cb81a7e-0662-4606-82fb-c3066b840831.png)
Is that what you mean?

2022-01-06 12:48 UTC, jancborchardt commented
> > maxcontrast
> 
> @jancborchardt ![image](https://user-images.githubusercontent.com/12224014/148232859-3cb81a7e-0662-4606-82fb-c3066b840831.png) Is that what you mean?

Exactly, looks much better! :) :+1:

2022-01-06 15:46 UTC, mgallien requested changes
a minor change inspired by the automated checks

2022-01-06 15:46 UTC, mgallien commented on src/gui/passwordinputdialog.h
> +    Ui::PasswordInputDialog *ui;
can you replace it with a smart pointer (most probably `std::unique_ptr`) ?

2022-01-10 10:12 UTC, allexzander commented
> a minor change inspired by the automated checks

@mgallien Fixed!

2022-01-10 12:04 UTC, jancborchardt approved these changes
:+1: design-wise :)

2022-01-11 15:36 UTC, mgallien approved these changes

2022-01-11 15:47 UTC, camilasan approved these changes

2022-01-12 09:19 UTC, mgallien commented
/rebase

2022-01-12 10:35 UTC, mgallien commented
/rebase

2022-01-12 11:05 UTC, mgallien commented
@alex can you squash the commits before merging ?

2022-01-12 11:35 UTC, merged