Feature/public links
nextcloud/desktop pull request #4175
Opened 2022-01-13 14:16 UTC by mgallien

2022-02-09 11:29 UTC, allexzander commented on src/gui/tray/usermodel.h
> +    void switchCurrentUser(const int &id);
@mgallien reference to in? does this help with performance?

2022-02-09 11:33 UTC, allexzander commented on src/gui/tray/usermodel.cpp
> +    return !_account->account()->isPublicShareLink();
@mgallien `return !isPublicShareLink();`

2022-02-09 11:38 UTC, allexzander commented
@mgallien How can this be tested?

2022-07-10 21:34 UTC, mgallien commented on src/gui/tray/usermodel.cpp
> +    return !_account->account()->isPublicShareLink();
done

2022-07-10 21:34 UTC, mgallien commented on src/gui/tray/UserLine.qml
> +                    height: visible ? implicitHeight : 0
this has already been done in other menu items
most probably a limitation of the `MenuItem` component

2022-07-10 21:35 UTC, mgallien commented
> @mgallien How can this be tested?

Using a nextcloud server you can create a public share link for a folder
With this link, use it as the server URL when adding a new account and it should just works

2023-09-15 08:31 UTC, fwcd commented
Any updates on this?

2024-10-18 07:35 UTC, lauff commented
Is this already working?

2025-01-23 10:41 UTC, nilsding requested changes
one small thing, really nice otherwise

side note: when I restarted the client I was prompted to sign in for the public share again, which doesn't really work ... but with the patch from #7768 applied it's fine

2025-01-23 10:41 UTC, nilsding commented on src/libsync/account.cpp
> +    const QRegularExpression discoverPublicLinks(R"((http.://[^/]*).*/s/([^/]*))");
would be nice to have plain `http://` links work too (e.g. for local dev)

```suggestion
    const QRegularExpression discoverPublicLinks(R"((https?://[^/]*).*/s/([^/]*))");
```

2025-10-02 09:53 UTC, mgallien commented on src/libsync/account.cpp
> +    const QRegularExpression discoverPublicLinks(R"((http.://[^/]*).*/s/([^/]*))");
done
we will accept `http` and `https` protocols

2025-10-02 10:01 UTC, nilsding approved these changes

2025-10-02 14:24 UTC, Aiiaiiio commented on src/gui/owncloudsetupwizard.cpp
> +        qCInfo(lcWizard()) << "seeting up public share link account";
```suggestion
        qCInfo(lcWizard()) << "setting up public share link account";
```

2025-10-02 14:25 UTC, Aiiaiiio commented on src/gui/tray/UserLine.qml
> +<<<<<<< HEAD
Oops

2025-10-02 14:32 UTC, Aiiaiiio commented on src/gui/tray/usermodel.cpp
> +    return !isPublicShareLink();
Without really knowing the context, reads very weird, that `canLogout()` doesn't care whether we are logged in.

2025-10-02 15:05 UTC, merged

2025-10-03 12:16 UTC, mgallien commented on src/gui/tray/UserLine.qml
> +<<<<<<< HEAD
thanks
already fixed