Bugfix/activities fetch server overload
nextcloud/desktop pull request #4441
Opened 2022-04-14 16:09 UTC by allexzander

2022-04-27 11:50 UTC, camilasan approved these changes

2022-04-29 15:13 UTC, mgallien requested changes

2022-04-29 16:31 UTC, allexzander commented on src/gui/tray/usermodel.h
> +    Q_PROPERTY(bool isTrayOpen READ isTrayOpen WRITE setIsTrayOpen NOTIFY isTrayOpenChanged)
@mgallien my bad, overlooked it, now should be fixed

2022-04-29 21:12 UTC, mgallien approved these changes

2022-04-29 21:12 UTC, merged