VCPKG Compile Script for Windows
nextcloud/desktop pull request #4652
Opened 2022-06-19 18:48 UTC by pvagnozzi

choco_setup.bat: script for install choco with old terminal.
choco_setup.ps1: script for install choco with power shell.
env_setup.ps1: script for install toolchain
compile.bat: script for compile the desktop client on windows using vcpkg and cmake.

2023-09-10 11:58 UTC, claucambra reviewed
I am not familiar with these tools so I have added team members who are familiar with them to review

2023-09-10 11:59 UTC, claucambra requested changes

2023-09-10 11:59 UTC, claucambra commented on vcpkg.json
> +  "homepage": "https://ftp.gnome.org/pub/GNOME/sources/pango/",
This is not Nextcloud's homepage :)

2023-09-16 09:28 UTC, mgallien requested changes
thanks
I would need to do a real test as I am not familiar with VCPKG
can you move the new files into a subdirectory inside `admin/win` (for example `admin/win/vcpkg`)

2023-09-16 09:42 UTC, mgallien requested changes

2023-09-16 09:42 UTC, mgallien commented on vcpkg.json
> +    "qt5-webview",
we use qt5-webengine so I think this one is wrong

2023-09-16 09:42 UTC, mgallien commented on vcpkg.json
> +    "qt5-webview",
see for example the current state as reported by cmake
```
-- The following OPTIONAL packages have been found:

 * Qt5WebChannel (required version >= 5.15)
 * Qt5Positioning (required version >= 5.15)
 * Qt5WebEngineCore (required version >= 5.15)
 * Qt5PrintSupport (required version >= 5.15)
 * Qt5LinguistTools
 * IcoTool

-- The following REQUIRED packages have been found:

 * OpenSSL (required version >= 1.1)
 * ZLIB
 * Qt5Concurrent (required version >= 5.15.0), Qt5 Concurrent component.
 * Qt5WebEngineWidgets (required version >= 5.15.0), Qt5 WebEngineWidgets component.
 * Qt5WebEngine (required version >= 5.15.0), Qt5 WebEngine component.
 * Qt5Keychain
 * SQLite3 (required version >= 3.8.0)
 * Qt5WebSockets
 * Qt5Widgets
 * Qt5Svg
 * Qt5QuickControls2
 * KF5Archive
 * Qt5Core, Qt5 Core component.
 * Qt5Test
 * Qt5Xml, Qt5 Xml component.
 * Qt5Network, Qt5 Network component.
 * Qt5Qml
 * Qt5QmlModels (required version >= 5.15.10)
 * Qt5Gui (required version >= 5.15.10)
 * Qt5Quick
 * Qt5
```

2023-09-16 09:42 UTC, mgallien commented on compile.bat
> +cmake --build . --config Debug --target install
not sure you would want debug builds by default

2024-08-03 10:24 UTC, closed without merging