Sharing feature for Nextmcloud
nextcloud/desktop pull request #4858
Opened 2022-08-18 12:39 UTC by TSI-pranalideshpande

In this ,we have harmonized the permission settings for sharing. Currently we have different options for internal, external and link shares as well as different option for files and folders.

1. We have added a radio button group containing the options for user(External) & sharelink for files and folder:
"Read only" (Nur Lesen)  
"Can edit" (Kann bearbeiten)  
we removed "can create", "can delete", 

2.for link share on folder we  have added one more option "Filedrop only"

3.Added dropdown containing the options of the radio button group for files and folder on user and share link 
"Read only" (Nur Lesen)  
"Can edit" (Kann bearbeiten)  

4. Sample screenshot of added dropdown is herewith

5. Its only UI related changes , we have covered actual changes on ticket #3&#4 for sharing , we will raised PR for same very soon.

2022-08-19 00:57 UTC, claucambra requested changes
Hi, the contributions are appreciated and this is something we might be interested in merging at some point, Unfortunately, this PR needs significant changes before that can be considered.

Chiefly, there are 3 major problems:

1. Style -- the style of the changes is inconsistent and often makes the code difficult to read. Please adapt your code to follow the style of the rest of the desktop client
2. Unrelated and unneeded changes -- I am not sure if this was caused by something such as a bad rebase of the branch, but this PR contains a significant amount of additions and changes that do not seem relevant to the changes mentioned in the description. Some of the changes that do seem related to the PR are also unclear (for instance, minute changes to window sizing in UI files). Please address this as at the moment this code is unmergeable and the CI pipelines for this PR are failing
3. Screenshots -- just looking at the code it is very difficult to tell how the UI has changed. Please provide media such as screenshots and screen recordings to demonstrate the changes so that reviewers on both the Desktop Client team and the Design Team can review the visual changes

2022-08-19 00:57 UTC, claucambra commented on admin/win/msi/RegistryCleanup.vbs
> +End Function
These changes seem unrelated

2022-08-19 00:57 UTC, claucambra commented on appveyor.ini
> +General/ABI = windows-msvc2019_64-cl
These changes also seem unrelated, it looks like there has been a mistake somewhere, maybe rebasing the branch?

2022-08-19 00:57 UTC, claucambra commented on appveyor.yml
> +    - TARGET: windows-msvc2019_64-cl
Once more these seem unrelated

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharedialog.ui
> +    <height>404</height>
I am not sure why the four extra pixels are needed here

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharedialog.ui
> +          <height>314</height>
Again, not sure why these tiny adjustments to the dialog size are needed?

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                        &ok);
The change in indentation seems unnecessary

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.ui
> +   </item>
Could you provide a screenshot showing the result of the changes made?

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                                           QWidget *parent)
This indentation change is wrong, indentation should remain as it was

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                                      _completer);
This indentation change does not seem necessary

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +            this, &ShareUserGroupWidget::slotLineEditTextEdited, Qt::QueuedConnection);
See my previous comment on indetation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                || sharee->shareWith() == text) {
More indentation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +
This does not seem necessary

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                    this, SLOT(slotPrivateLinkCopy()));
indentation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                          sharee->shareWith(), _maxSharingPermissions, password);
indentation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                this);
indentation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +                             SharePermissions maxSharingPermissions, bool isFile, QWidget *parent)
indentation

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareuserline.ui
> +    <height>544</height>
If a size change is necessary, I would say it would be better to choose round numbers IMO

2022-08-19 00:57 UTC, claucambra commented on theme/colored/Nextcloud-sidebar.svg
> +</svg>
Again, doesn't seem related

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.ui
> +    <height>112</height>
This size change seems unnecessary

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.cpp
> +         _linkContextMenu->addAction(_allowUploadEditingLinkAction);
```suggestion
        _linkContextMenu->addAction(_allowUploadEditingLinkAction);
```

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.cpp
> +        }
This does not fit the style of other conditional statements throughtout the desktop client (see the parent `if` statements for instance)

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.cpp
> +         _ui->currentPermission_3->setText(action->text());
```suggestion
        _ui->currentPermission_3->setText(action->text());
```

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.cpp
> +         _ui->currentPermission_3->setText(action->text());
```suggestion
        _ui->currentPermission_3->setText(action->text());
```

2022-08-19 00:57 UTC, claucambra commented on src/gui/sharelinkwidget.cpp
> +        _allowUploadLinkAction = permissionsGroup->addAction(tr("File drop"));
I think the previous string was better, more descriptive

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +    //    permissionMenu->setStyleSheet(menuStyle);
If this is not needed please remove

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
>      _permissionReshare= new QAction(tr("Can reshare"), this);
```suggestion
    _permissionReshare = new QAction(tr("Can reshare"), this);
```

2022-08-19 00:57 UTC, claucambra commented on src/gui/shareusergroupwidget.cpp
> +            && share->account()->serverVersionInt() < Account::makeServerVersion(9, 1, 0)) {
indentation

2022-08-22 12:27 UTC, TSI-pranalideshpande commented
Hi ,Thanks for the review , I observed some issues in rebasing and while creating pull request for this branch  some files are unnecesarily raised for PR , I am planing to  create new branch and then will raise pr for that.

2022-11-09 15:56 UTC, claucambra commented
Closing now that #4929 has been merged and this is not compatible

2022-11-09 15:56 UTC, closed without merging