Fix File Activities dialog not showing up.
nextcloud/desktop pull request #4867
Opened 2022-08-25 14:07 UTC by allexzander

Signed-off-by: alex-z <blackslayer4@gmail.com>

2022-08-25 14:12 UTC, claucambra requested changes
This breaks window positioning on some OSes (like macOS)

The window appears under the system tray window and also behind other windows

2022-08-25 14:35 UTC, allexzander commented
@claucambra Any ideas on how to fix it alternatively, such that we don't have a bug of this dialog not showing up until manually opening the Systray as it happens now on Windows?

2022-08-25 14:39 UTC, allexzander commented
@claucambra I've added a video demonstration to the description

2022-08-25 19:09 UTC, claucambra commented
> @claucambra Any ideas on how to fix it alternatively, such that we don't have a bug of this dialog not showing up until manually opening the Systray as it happens now on Windows?

It is almost certain that the issue is with `forceWindowInit`, specifically the Windows-only code in `systray.cpp` lines 431 and 432

I am not sure why this is an issue for the file activity dialog window and not for other windows (maybe those get a call to `show` again somewhere?) It does at least seem to be something straightforward to fix or work around

2022-08-26 07:59 UTC, allexzander commented
> > @claucambra Any ideas on how to fix it alternatively, such that we don't have a bug of this dialog not showing up until manually opening the Systray as it happens now on Windows?
> 
> It is almost certain that the issue is with `forceWindowInit`, specifically the Windows-only code in `systray.cpp` lines 431 and 432
> 
> I am not sure why this is an issue for the file activity dialog window and not for other windows (maybe those get a call to `show` again somewhere?) It does at least seem to be something straightforward to fix or work around

Yes, I have tried fixing the show/hide code in CPP, and it didn't help. Now I have changed the order of calls in QML and it seems to have fixed the issue. Let me know your thoughts.

2022-08-26 12:51 UTC, mgallien approved these changes

2022-08-26 18:21 UTC, claucambra approved these changes
This works fine on macOS and KDE :)

2022-08-29 08:29 UTC, merged