Fix two factor authentication notification
nextcloud/desktop pull request #4967
Opened 2022-09-21 15:24 UTC by camilasan

Fix for #4841

2022-09-26 11:50 UTC, jancborchardt commented
@camilasan nice! :) Do you mind posting a screenshot for a much quicker design review? Thank you!

2022-09-26 11:52 UTC, jancborchardt approved these changes
If it’s the screenshot from https://github.com/nextcloud/desktop/issues/4841#issuecomment-1252767634, looks good! :)

The message does mention "Approve or deny" but the buttons are only "Approve" or "Cancel", so maybe they should be named accordingly?

2022-09-26 12:32 UTC, claucambra commented on src/gui/tray/ActivityItemActions.qml
>              bold: primary
IMO this should now be decided internally by the `ActivityActionButton`, where `property bool bold: primaryButton`, as we never set it to anything different here

2022-09-26 12:32 UTC, claucambra commented on src/gui/tray/ActivityItemActions.qml
> +            textColorHovered: imageSource !== "" || primary ? UserModel.currentUser.headerTextColor : Style.ncTextColor
Throughout `ActivityItemActions` we are now basically always using the `CustomButton` for a situation where we have a primary button (before we would use `primary` to ensure we bolded the first button in the `CustomTextButton`)

Now that we always set things with `imageSource` and `primary` together, can we not just integrate `imageSource !== ""` into the `primary` property?

2022-09-26 13:16 UTC, allexzander approved these changes

2022-09-26 16:22 UTC, claucambra requested changes
A couple of small details

2022-09-26 16:22 UTC, claucambra commented on src/gui/tray/ActivityItemActions.qml
> +            textColor:  primary ? root.adjustedHeaderColor : Style.ncTextColor
```suggestion
            textColor: primary ? root.adjustedHeaderColor : Style.ncTextColor
```

2022-09-26 16:23 UTC, claucambra commented
@camilasan It seems to work great for most notifications except missed call notifications, where we now have two primary buttons:

![Screenshot 2022-09-26 at 18 22 09](https://user-images.githubusercontent.com/70155116/192329987-5dd4a177-69e8-4e97-b1d3-631660077d71.png)

I am guessing this is not intentional?

2022-09-27 09:54 UTC, jancborchardt commented
At some point, "Reply" would also be good to have in call notifications for server. cc @nickvergessen 

In the case of call notifications, "Call back" would be primary, "Reply" secondary.
For messages, "Reply" should stay primary of course.

2022-09-27 10:26 UTC, nickvergessen commented
> At some point, "Reply" would also be good to have in call notifications for server.

https://github.com/nextcloud/notifications/issues/637

2022-09-27 12:09 UTC, claucambra approved these changes

2022-09-27 12:09 UTC, claucambra commented
looks good now

2022-09-27 14:52 UTC, merged