use correct version copmparison on NSIS updater: fix update from rc
nextcloud/desktop pull request #4979
Opened 2022-09-27 18:01 UTC by mgallien

Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

2022-09-28 07:33 UTC, allexzander commented on src/gui/updater/ocupdater.cpp
> +        qint64 currentVer = Helper::currentVersionToInt();
`const auto`

2022-09-28 07:33 UTC, allexzander commented on src/gui/updater/ocupdater.cpp
> +        qint64 remoteVer = Helper::stringVersionToInt(info.version());
same

2022-09-28 07:34 UTC, allexzander commented on src/gui/updater/ocupdater.cpp
> +            QString url = info.downloadUrl();
`const auto`

2022-09-28 07:36 UTC, allexzander commented on src/gui/updater/ocupdater.cpp
> +    qCInfo(lcUpdater()) << "received a reply";
`qCInfo(lcUpdater())` -> `qCInfo(lcUpdater)`

2022-09-28 07:47 UTC, allexzander requested changes
@matthieugallien 
Besides some nitpicks, I've got question:

What about the feature of skipping a certain version? I see that now `seenVersion` is no longer in use, is this expected? Also, if this is the case, the entire code for `seenVersion` needs to be removed as well to avoid confusion?

2022-09-28 09:43 UTC, mgallien commented
> @matthieugallien Besides some nitpicks, I've got question:
> 
> What about the feature of skipping a certain version? I see that now `seenVersion` is no longer in use, is this expected? Also, if this is the case, the entire code for `seenVersion` needs to be removed as well to avoid confusion?

I am not convinced we should fix the current interface to tell users about the skipped version. I would prefer to remove it altogether as we should aim to produce new versions that are not broken and skipping an update should never be needed.

2022-10-05 08:11 UTC, allexzander approved these changes

2022-10-12 11:43 UTC, merged

2022-10-18 08:36 UTC, mgallien commented
/backport to stable-3.6