Fix account not found when doing local file editing.
nextcloud/desktop pull request #5040
Opened 2022-10-13 08:27 UTC by allexzander

Signed-off-by: alex-z <blackslayer4@gmail.com>

2022-10-13 10:09 UTC, claucambra approved these changes

2022-10-13 10:09 UTC, claucambra commented on src/gui/accountmanager.cpp
> +    const auto it = std::find_if(_accounts.cbegin(), _accounts.cend(), [davUserNameAndHostSplit](const auto &acc) {
```suggestion
    const auto it = std::find_if(_accounts.cbegin(), _accounts.cend(), [&davUserNameAndHostSplit](const auto &acc) {
```

2022-10-13 15:07 UTC, mgallien reviewed
partial review pending more thorough review

2022-10-14 08:33 UTC, mgallien commented on src/libsync/account.cpp
> +            return _davUser;
this is wrong for something that will be a display name
`_davUser` is the user backend internal id coming from server and should never be display to teh user

2022-10-14 08:35 UTC, mgallien requested changes
the changes to `Account::displayName()` are wrong
display name has nothing to do with the user id stored in `_davUser`

2022-10-17 09:24 UTC, mgallien approved these changes
thanks

2022-10-17 11:56 UTC, merged