Add support cmake unity build
nextcloud/desktop pull request #5109
Opened 2022-10-29 00:54 UTC by tnixeu

This PR prepares building with `CMAKE_UNITY_BUILD` enabled. This makes builds often a bit faster and the executables often a bit smaller.

I tried to keep the changes as small as possible and without renaming variables. This is why I exclude the file causing troubles from the unity build or added macros in order to avoid defining a variable multiple times. 

I timed the builds with `time ninja`

Unity build:  nextcloud 5.6M
```
real    0m42,137s
user    3m36,684s
sys     0m17,226s
```

Normal build: nextcloud 5.8M
```
real    0m46,048s
user    9m13,199s
sys     0m45,951s
```

2022-10-29 09:18 UTC, tnixeu commented
I logged in with this version, synced a view files. It seems fine by me.

None of my changes should currently have an impact at runtime, because the Appimage is probably not yet built with `CMAKE_UNITY_BUILD` turned on.

2022-11-09 08:53 UTC, mgallien requested changes
thanks a lot that is nice
would you like to also try activating it for the AppImage ?
I can help and guide you if you want

2022-11-09 08:53 UTC, mgallien commented on src/gui/folder.cpp
> +#endif
please can you replace them by the following code
```
namespace {
constexpr auto versionC= "version";
}
```
can you also apply the same solution to the few other occurrences

2022-11-09 08:58 UTC, mgallien commented on src/gui/folder.cpp
> +#endif
please ignore that comment
it is indeed not compiling
so please use
```
namespace {
#ifndef VERSION_C
#define VERSION_C
constexpr auto versionC= "version";
#endif
}
```

2022-11-09 09:01 UTC, mgallien commented
I am also getting a build failure if the `dolphin` native plugin is getting build due to a conflict between `signals` macro from Qt headers and some code in this header `/usr/include/glib-2.0/gio/gdbusintrospection.h`
maybe you could also add this file `src/3rdparty/kmessagewidget/kmessagewidget.cpp` to the list of files not included in unity builds ?

2022-11-09 09:02 UTC, mgallien commented
> I logged in with this version, synced a view files. It seems fine by me.
> 
> None of my changes should currently have an impact at runtime, because the Appimage is probably not yet built with `CMAKE_UNITY_BUILD` turned on.

You would need to add the extra configure option in this file https://github.com/nextcloud/desktop/blob/master/admin/linux/build-appimage.sh

2022-11-14 07:42 UTC, mgallien approved these changes
thanks

2022-11-14 08:42 UTC, merged