Clearly tell user that E2EE has been enabled for an account
nextcloud/desktop pull request #5164
Opened 2022-11-10 16:16 UTC by claucambra

Part of https://github.com/nextcloud/desktop/issues/5126

Signed-off-by: Claudio Cambra <claudio.cambra@nextcloud.com>

2022-11-14 23:28 UTC, jancborchardt requested changes
Nice! :) Just the icons are a bit off:
- The checkmark icon shouldnt be the "All synced" icon
- The info icon looks a bit oldish

Similar like for "General" and "Network", could we use native icons for each of them which work for the platform?

Otherwise as quick fixes:
- E2E active, a lock: https://fonts.google.com/icons?selected=Material%20Icons%3Alock%3A
- E2E possible, info i: https://fonts.google.com/icons?selected=Material%20Icons%3Ainfo%3A

2022-11-15 11:04 UTC, claucambra commented on src/gui/accountsettings.cpp
> +    _ui->encryptionMessage->setText(tr("End-to-End encryption has been enabled for this account"));
Yes, I think so, as the server supports several types of encryption systems and "encryption" is not clear which one

2022-11-15 11:29 UTC, claucambra commented
> Nice! :) Just the icons are a bit off:
> 
> * The checkmark icon shouldnt be the "All synced" icon
> * The info icon looks a bit oldish
> 
> Similar like for "General" and "Network", could we use native icons for each of them which work for the platform?
> 
> Otherwise as quick fixes:
> 
> * E2E active, a lock: https://fonts.google.com/icons?selected=Material%20Icons%3Alock%3A
> * E2E possible, info i: https://fonts.google.com/icons?selected=Material%20Icons%3Ainfo%3A

Okay, I have changed the icons used in the message box and updated the screenshots above 🙂

Ad for native icons more generally, let's open a separate issue for this

2022-11-15 11:32 UTC, claucambra commented on src/gui/accountsettings.cpp
> +
Removed

2022-11-15 11:36 UTC, claucambra commented on src/gui/accountsettings.cpp
> +
removed

2022-11-15 11:38 UTC, claucambra commented on src/gui/accountsettings.cpp
> +    _ui->encryptionMessage->setText(tr("End-to-End encryption has been enabled for this account"));
Then again, if it is a contextual string (e.g. a messagebox message) that should be clear enough

2022-11-15 14:54 UTC, jancborchardt commented on src/gui/accountsettings.cpp
> +    _ui->encryptionMessage->setText(tr("End-to-End encryption has been enabled for this account"));
Btw, the wording or capitalization should be End-to-end encryption, with lowercase second e. And if in a sentence, the first e should be lowercase as well of course.

2022-11-15 15:51 UTC, claucambra commented on src/gui/accountsettings.cpp
> +    _ui->encryptionMessage->setText(tr("End-to-End encryption has been enabled for this account"));
Thanks, this is now done :)

2022-11-15 17:40 UTC, jancborchardt approved these changes
Noice! :)

2022-11-16 14:10 UTC, tobiasKaminsky commented
Not sure if it is still valid, but in second screenshot:
I assume that account has no E2E yet, so button might better be "setup" instead of "enable e2e" to distinguish this more.

2022-11-24 11:05 UTC, claucambra commented
> Not sure if it is still valid, but in second screenshot:
> I assume that account has no E2E yet, so button might better be "setup" instead of "enable e2e" to distinguish this more.

changed :)

2022-11-25 13:10 UTC, merged