Add ability to disable E2EE
nextcloud/desktop pull request #5167
Opened 2022-11-11 20:38 UTC by claucambra

This PR adds the ability to disable E2EE through the account settings. It deletes encrypted files that are locally synced when E2EE is disabled.

https://user-images.githubusercontent.com/70155116/201427231-122c1acb-964d-46af-a720-3e44a19cd43b.mov

TODO: [ ] testing

2022-12-09 11:02 UTC, mgallien requested changes
`FolderManTest` test is crashing
can you have a look ?

2022-12-09 11:50 UTC, claucambra commented
> `FolderManTest` test is crashing
> can you have a look ?

fixed

2022-12-09 15:32 UTC, mgallien commented
> > `FolderManTest` test is crashing
> > can you have a look ?
> 
> fixed

I will try to have another look today

2022-12-19 16:46 UTC, allexzander requested changes

2022-12-19 16:46 UTC, allexzander commented on src/gui/folder.cpp
> +void Folder::removeLocalE2eFiles()
@claucambra We should use selective sync blacklist and rely on a sync engine to remove files that we can't use.

2022-12-30 15:21 UTC, claucambra commented on src/libsync/discovery.cpp
> +            _discoveryData->_account->e2e() && !_discoveryData->_account->e2e()->_publicKey.isNull() && _discoveryData->_account->e2e()->_privateKey.isNull();
I would put each of these on a separate line for readbility

2022-12-30 15:21 UTC, claucambra commented on src/gui/folder.cpp
> +        foreach (const auto &it, changes) {
I would not use `foreach` in new code, `for(const auto &x : y)` is better

2023-01-06 17:08 UTC, mgallien commented
@claucambra there are build issues in the drone check and sonarcloud analysis failed due to failing tests

2023-01-09 14:52 UTC, claucambra commented
> @claucambra there are build issues in the drone check and sonarcloud analysis failed due to failing tests

Fixed

2023-01-24 14:46 UTC, allexzander approved these changes

2023-01-24 16:35 UTC, merged