Fix SyncEngineTest failure when localstate is destroyed.
nextcloud/desktop pull request #5273
Opened 2022-12-13 13:41 UTC by allexzander

Signed-off-by: alex-z <blackslayer4@gmail.com>

2022-12-13 13:51 UTC, claucambra approved these changes

2022-12-13 13:57 UTC, mgallien requested changes

2022-12-13 13:57 UTC, mgallien commented on test/testsyncengine.cpp
> +        QCOMPARE(localState, fakeFolder.currentRemoteState());
not sure I get why we need to do a copy here ?
do you have a stack of the error ?

2022-12-15 09:37 UTC, mgallien approved these changes

2022-12-15 10:10 UTC, merged

2023-01-18 12:28 UTC, allexzander commented
/backport to stable-3.6