If file has not changed but Etag has, this change must be reflected n the local db
nextcloud/desktop pull request #5280
Opened 2022-12-16 16:37 UTC by allexzander

Signed-off-by: alex-z <blackslayer4@gmail.com>

2022-12-16 16:42 UTC, claucambra approved these changes
Just a small comment, looks good

2022-12-16 16:42 UTC, claucambra commented on src/libsync/propagatedownload.cpp
> +    const auto etagChangedButFileHasNotChanged = propagator()->_journal->getFileRecord(_item->_file, &record) && record.isValid()
I would put each condition in a separate line for readability

2022-12-19 11:22 UTC, mgallien requested changes
this should come with changes in the automated tests
otherwise this could break or be broken in the future

2022-12-20 15:05 UTC, allexzander commented
> this should come with changes in the automated tests otherwise this could break or be broken in the future
Agree, and I should have used a completely another way.

2022-12-20 18:49 UTC, closed without merging

2022-12-20 18:50 UTC, allexzander commented
Continue working on it in a new PR https://github.com/nextcloud/desktop/pull/5293