Exclude NavigationPaneHelper from non-Windows compile
nextcloud/desktop pull request #5288
Opened 2022-12-19 16:08 UTC by claucambra

Since NavigationPaneHelper only includes functionality relevant to Windows and its introduction causes compile warnings on other platforms, this PR excludes the NPH from non-Windows builds

The ifdefs that cause warnings on other platforms have been modified to fix them if in the future NavigationPaneHelper is used on other platforms too

2025-03-13 03:25 UTC, claucambra commented
> @claucambra can you fix the conflicts ?

Thanks, done

2025-03-13 07:22 UTC, nilsding requested changes
looks good, but there is also another usage of `navigationPaneHelper`:

```
src/gui/accountsetupfromcommandlinejob.cpp
179:    if (folderMan->navigationPaneHelper().showInExplorerNavigationPane()) {
```

2025-03-14 03:06 UTC, claucambra commented
> looks good, but there is also another usage of `navigationPaneHelper` that breaks compilation:
> 
> ```
> src/gui/accountsetupfromcommandlinejob.cpp
> 179:    if (folderMan->navigationPaneHelper().showInExplorerNavigationPane()) {
> ```

Thanks, fixed

2025-03-14 07:05 UTC, nilsding approved these changes

2025-04-15 09:07 UTC, merged