Ensure errors are displayed as first entries in tray window activity list
nextcloud/desktop pull request #5408
Opened 2023-02-06 16:52 UTC by claucambra

At the moment they are often pushed way down the list below less important entries such as notifications due to their activity type

With this PR we ensure they are first on the list

With this PR:

<img width="497" alt="Screenshot 2023-02-06 at 17 50 38" src="https://user-images.githubusercontent.com/70155116/217033773-84933f06-b412-48a9-a8f7-a92983a25fec.png">

Master:

https://user-images.githubusercontent.com/70155116/217033814-cb8f68da-c77a-4693-9bdf-6cd99fae826f.mov

2023-02-06 16:53 UTC, claucambra commented
/backport to stable-3.7

2023-02-28 15:08 UTC, mgallien requested changes
this is missing automated tests

2023-03-01 15:34 UTC, claucambra commented
> this is missing automated tests

Took a lot of changes to not duplicate masses of code, but the sort order is now fully tested (and the sortedactivitylistmodel in general)

2023-07-24 11:54 UTC, allexzander approved these changes

2023-07-25 01:59 UTC, merged