Windows: Additional write permissions check
nextcloud/desktop pull request #5510
Opened 2023-03-09 12:15 UTC by Alkl58

The Problem: The [isWritable()](https://doc.qt.io/qt-6/qfileinfo.html#isWritable) function checks only(?) for write [permissions](https://doc.qt.io/qt-6/qfiledevice.html#Permission-enum) for the user, owner, group or anyone(?). 

**Its technically correct** - when opening the folder permissions of an SMB share in Explorer, it shows that the user doesn't have those permissions. The actual permission for being able to read/write/delete is not covered by the "base" permissions of Explorer, it's covered by the "special permissions". 

It looks similar to this (just imageine it being an SMB share):
 ![](https://i.stack.imgur.com/du8D5.png)

**For more info check my comment:** https://github.com/nextcloud/desktop/issues/3910#issuecomment-1460924930

This PR adds an additional actual write test for Windows hosts.

This PR fixes #3910 

_First time using C++, comments/improvements welcome!_

2023-03-09 13:50 UTC, Alkl58 commented
Also closes/fixes: #3201

2023-03-09 14:53 UTC, Alkl58 commented
Test on SMB share:
![grafik](https://user-images.githubusercontent.com/34812414/224059938-ad36cbc2-8aa6-46fb-8e04-946a16cf70d0.png)

Test on normal folder:
![grafik](https://user-images.githubusercontent.com/34812414/224060365-e80e53b2-0fb6-4891-8e15-f1eae280ad5a.png)

Test on protected system folder:
![grafik](https://user-images.githubusercontent.com/34812414/224060122-5b9bb2b5-46bb-4127-87b4-8d7da279b481.png)

Test on write protected folder:
![grafik](https://user-images.githubusercontent.com/34812414/224060647-6923edbe-ffcd-4470-9752-1d8657162b83.png)

2023-03-13 15:25 UTC, Alkl58 commented
Will this be merged at some point? Or should I close it?

2023-03-13 17:07 UTC, claucambra reviewed
It looks good at first glance, but need to find time to test

2023-05-06 05:24 UTC, claucambra requested changes
A couple of small comments

2023-05-06 05:24 UTC, claucambra commented on src/gui/folderman.cpp
> +        FILE *fp = fopen(testPath.c_str(), "w");
```suggestion
        const auto fp = fopen(testPath.c_str(), "w");
```

2023-05-06 05:24 UTC, claucambra commented on src/gui/folderman.cpp
> +        auto testPath = path.toStdString() + "\\nextcloud-write-test-file.txt";
```suggestion
        const auto testPath = path.toStdString() + "\\nextcloud-write-test-file.txt";
```

2023-05-06 05:24 UTC, claucambra commented on src/gui/folderman.cpp
> +            return FolderMan::tr("You have no permission to write to the selected folder!");
```suggestion
        if (!fp) {
            return FolderMan::tr("You have no permission to write to the selected folder!");
        }
```

2023-05-06 05:24 UTC, claucambra commented on src/gui/folderman.cpp
> +        auto rc = remove(testPath.c_str());
```suggestion
        const auto rc = remove(testPath.c_str());
```

2023-05-06 05:24 UTC, claucambra commented on src/gui/folderman.cpp
> +            return FolderMan::tr("You have no permission to write to the selected folder!");
```suggestion
        if (rc) {
            return FolderMan::tr("You have no permission to write to the selected folder!");
        }
```

2023-10-22 08:40 UTC, claucambra requested changes
Hi @Alkl58 are you able to make the requested changes? If not we are happy to take over the PR and include your changes with our own fixes :)

2023-11-06 15:43 UTC, Alkl58 commented
> Hi @Alkl58 are you able to make the requested changes? If not we are happy to take over the PR and include your changes with our own fixes :)

Sorry for the delay. Should be all good now :)

2023-11-06 17:51 UTC, allexzander requested changes

2023-11-06 17:51 UTC, allexzander commented on src/gui/folderman.cpp
> +        const auto fp = fopen(testPath.c_str(), "w");
const auto fp = fopen(testPath.toStdWString().c_str(), "w");

2023-11-06 17:51 UTC, allexzander commented on src/gui/folderman.cpp
> +        const auto rc = remove(testPath.c_str());
const auto rc = remove(testPath.toStdWString().c_str());

2023-11-07 15:03 UTC, allexzander commented
> Just a FYI: Apparently I completely broke my local dev environment after trying to install all qt dependencies. I'll reinstall my system / use a VM, will take some time so I can properly debug / fix things.

sure, no worries, I've noticed you're using `fopen` function from C, that only takes `const char*` as filename. We need to use `QFile` instead. If you are ok, I can take over the PR and incorporate changes.

2023-11-07 15:26 UTC, Alkl58 commented
@allexzander sure, thats probably faster, sorry for the hassle

2023-11-08 16:39 UTC, allexzander commented
Moved to https://github.com/nextcloud/desktop/pull/6209

2023-11-08 16:39 UTC, closed without merging