Fix for network validation issues on wireless (fixes Issue #4331)
nextcloud/desktop pull request #5542
Opened 2023-03-22 00:48 UTC by owenjm

There is an issue on linux (and maybe other OSes?) where reconnecting to the wifi network leads to a network validation error (unsure why, but previous code comments suggest it stems from an issue in QNAM).  See Issue #4331 for more details and comments.

This PR uses the procedure from `gui/networksettings.cpp` to force a fresh connection attempt following a validation error.  This ultimately leads to code in `AccountState::checkConnectivity()` that appears to have added to catch very similar issues (but was never reached in this error case).

2023-03-28 04:01 UTC, claucambra reviewed
Small nitpick, but otherwise looks ok :)

2023-03-28 04:01 UTC, claucambra commented on src/gui/creds/webflowcredentials.cpp
> +	}
```suggestion
	    for (auto account : accounts) {
	        account->freshConnectionAttempt();
	    }
```

2023-04-03 11:29 UTC, EmixamPP commented
This fix solved the problem for me too

2023-04-14 16:19 UTC, claucambra approved these changes

2023-04-26 10:36 UTC, mgallien requested changes

2023-04-26 10:36 UTC, mgallien commented on src/gui/creds/webflowcredentials.cpp
> +	    }
should you not call this only if the error is related to network issues ?
for example, imagine the desktop client doing a get request that will return a `404` result code, you do nto want to execute `freshConnectionAttempt()` after a `404`

an easy way to spot the issue is to have a client wihtout end-to-end encryption enabled but a server with the app installed and enabled

then if you open the settings dialog, we check if the server has a public end-to-end encryption key, gets a `404` and disconnects the session turning the tray icon to the disconnected state for some time before turning connected again

second thing is that most probably such a fix would be needed for all credentials classes not only when using the web flow v2 related code (i.e. this `WebFlowCredentials` class) but also other authentication methods

2023-06-27 13:23 UTC, timinator2020 commented
Do you have any estimation of which client version this will make it into? I have this problem on all of my Windows 10 and Linux Mint clients.

2024-05-28 10:03 UTC, Svampebob1 commented
Hi. I also have this issue and are hoping for a fix soon.

2024-07-25 20:48 UTC, bobbles911 commented
This fixes for me. Please include it as it's kind of broken without. Who wants a sync tool that constantly goes offline?!

2024-12-20 15:35 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-20 15:35 UTC, closed without merging