properly preserve the format of e2ee metadata during DB operations
nextcloud/desktop pull request #5577
Opened 2023-04-05 16:31 UTC by mgallien

before this patch we may put the e2ee version format to v1.2 when it was not the case

2023-04-05 19:21 UTC, allexzander requested changes

2023-04-06 08:42 UTC, mgallien commented on src/libsync/syncfileitem.cpp
> +    rec._isE2eEncrypted = static_cast<SyncJournalFileRecord::EncryptionStatus>(_isEncrypted);
to save the day of people affected by the bugs in `3.8.0` release, I am seriously considering changing the two enums in a way that would make them incompatible
so I am not sure what to do

2023-04-06 10:55 UTC, claucambra approved these changes

2023-04-06 10:58 UTC, allexzander commented on src/libsync/discovery.cpp
> +                item->_e2eEncryptionStatus = SyncFileItem::EncryptionStatus::Encrypted;
@mgallien should not you use a method `SyncFileItem::EncryptionStatus fromDbEncryptionStatus(SyncJournalFileRecord::EncryptionStatus encryptionStatus)` here?

2023-04-11 21:12 UTC, mgallien commented on src/libsync/syncfileitem.cpp
> +    rec._isE2eEncrypted = static_cast<SyncJournalFileRecord::EncryptionStatus>(_isEncrypted);
done

2023-04-12 08:32 UTC, allexzander commented on src/libsync/syncfileitem.h
> +    [[nodiscard]] bool isEncrypted() const { return _e2eEncryptionStatus != SyncFileItem::EncryptionStatus::NotEncrypted; }
`SyncFileItem::EncryptionStatus::NotEncrypted` -> `EncryptionStatus::NotEncrypted`

2023-04-12 09:15 UTC, allexzander approved these changes

2023-04-12 16:31 UTC, merged

2023-04-12 16:32 UTC, mgallien commented
/backport to stable-3.8