Fix crash on entering new log file after file size of 512kb reached
nextcloud/desktop pull request #5603
Opened 2023-04-13 10:52 UTC by claucambra

We are encountering a possible thread-unsafe race condition. Fix is to put this under the existing mutex.

2023-04-13 13:46 UTC, mgallien approved these changes

2023-04-13 13:46 UTC, mgallien commented
/backport to stable-3.8

2023-04-13 13:47 UTC, mgallien requested changes
deadlock

2023-04-19 09:10 UTC, allexzander approved these changes

2023-04-21 10:15 UTC, merged

2023-04-21 11:03 UTC, mgallien commented
/backport to stable-3.8