Modernise ignorelisttablewidget code
nextcloud/desktop pull request #5681
Opened 2023-05-11 13:02 UTC by claucambra

2025-03-12 13:42 UTC, mgallien requested changes

2025-03-12 13:42 UTC, mgallien commented on src/gui/ignorelisttablewidget.h
> +    int addPattern(const QString &pattern, const bool deletable, const bool readOnly);
please remove the `const` qualifier for POD data types as they must not be in the declaration interface for the methods, only the implementation

they do not change the signature for a caller (the generated symbol in the shared library does not include them)
they are an implementation detail

2025-03-13 03:13 UTC, claucambra commented on src/gui/ignorelisttablewidget.h
> +    int addPattern(const QString &pattern, const bool deletable, const bool readOnly);
Thanks, fixed

2025-03-14 14:01 UTC, mgallien approved these changes

2025-03-14 15:39 UTC, merged