Nmc/style sheet changes
nextcloud/desktop pull request #5776
Opened 2023-06-07 09:12 UTC by TSI-parulsharma

Did changes related to style sheet.
Added global style sheet file style.qss
Styling toolbar and progress bar using style.qss

2023-06-12 08:20 UTC, TSI-parulsharma commented on resources.qrc
> +	<qresource prefix="/qss">
I added this qss resource file using Qt Creator add prefix and Add file button.

2023-06-12 08:21 UTC, TSI-parulsharma commented on src/gui/settingsdialog.cpp
> +    //_toolBar->setProperty(background, palette().base().color().name());
Fixed

2023-06-12 08:21 UTC, TSI-parulsharma commented on src/gui/folderwizard.cpp
> +    this->setObjectName("folderWizard");
Fixed

2023-06-12 08:21 UTC, TSI-parulsharma commented on src/gui/application.cpp
> +    this->setStyleSheet(styleSheet.arg(background, dark, highlightColor, highlightTextColor));
Fixed

2023-06-12 08:21 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
> +    if (backButton) {
Fixed

2023-06-12 08:22 UTC, TSI-parulsharma commented on theme/Style/style.qss
> +QProgressBar {border: 1px solid grey; border-radius: 5px; text-align: center;}
Fixed

2023-06-12 08:22 UTC, TSI-parulsharma commented on src/gui/application.h
> +    void setCustomStyleSheet();
Fixed

2023-06-12 08:22 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
>          if (nextButton) {
Fixed

2023-06-12 08:22 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
>          auto nextButton = qobject_cast<QPushButton *>(button(QWizard::NextButton));
Fixed

2023-06-29 16:44 UTC, mgallien requested changes
see my inline comments

2023-06-30 06:44 UTC, TSI-parulsharma commented on src/gui/application.cpp
> +        QString styleSheet = QLatin1String(file.readAll());
Yes correct! I fixed it :)

2023-06-30 06:48 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
> +        backButton->setObjectName("backButton");
We want to change the styles of this button as per our customization from style.qss. To access in style.qss, we need indentifier. If we set the object name in NextCloud original code then modification will not be required in these files for customization. We can directly change the styles from style.qss

2023-06-30 07:04 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
> +        backButton->setDefault(true);
I think we can have two default buttons on QWizardPages. We ran the code and tested properly. We did this only to set the object name to change the default styling of this button. If you want we can remove line 310(backButton->setDefault(true);).

2023-06-30 07:04 UTC, TSI-parulsharma commented on src/gui/wizard/owncloudwizard.cpp
> +            nextButton->setObjectName("nextButton");
We want to change the styles of this button as per our customization from style.qss. To access in style.qss, we need indentifier.

2023-06-30 07:04 UTC, TSI-parulsharma commented on src/gui/folderwizard.cpp
> +    setObjectName("folderWizard");
We want to change the styles of this button as per our customization from style.qss. To access in style.qss, we need indentifier.

2023-07-07 07:17 UTC, mgallien approved these changes

2023-07-07 07:18 UTC, mgallien commented
@TSI-parulsharma sorry for the delay, this slipped out of my mind
we have a DCO check that is failing
see https://github.com/nextcloud/desktop/pull/5776/checks?check_run_id=14788692861
I can help if needed

2023-08-15 07:46 UTC, tsdicloud commented
Does anybody understand the purpose of this PR?
I think it missed the actual topic of more flexible theming...

Any idea how to proceed?

2023-08-20 10:36 UTC, tsdicloud commented
I don't understand why individual changes from MagentaCLOUD should be upstreamed.
The stylesheet mechanism is maybe nice (although I am not completely convinced anymore as it is only a complicated version of and added QStyle class...

MagentaCLOUD should not upstream things that may need to change on demand, as it would then mean to always ask for an upstream change. Let's discuss this F2F as planned.

2024-11-05 08:59 UTC, closed without merging