update account settings storage design
nextcloud/desktop pull request #5849
Opened 2023-06-29 14:25 UTC by AnkurBavisa

update account settings storage design.
![NextCloud_After](https://github.com/nextcloud/desktop/assets/103042752/9e2d6bb9-b429-4724-9f82-4654d4c6a242)
![NextCloud_Before](https://github.com/nextcloud/desktop/assets/103042752/151d76ba-3863-4be9-98a7-ed626885a686)

2023-06-30 05:59 UTC, claucambra requested changes

2023-06-30 05:59 UTC, claucambra commented on src/gui/accountsettings.cpp
> +    _ui->quotaProgressLabel->setVisible(false);
This is not something we want for the vanilla client

2023-07-03 07:11 UTC, AnkurBavisa commented
> @AnkurBavisa could you share the screenshots of the running client (end result) with your change? I think then it will be easy for @jancborchardt to review that.

![NC_UI_New](https://github.com/nextcloud/desktop/assets/103042752/d9441bfe-cbd0-4f94-a485-a1436da5902f)
![NC_UI_Progressbar_Temporary_Enable](https://github.com/nextcloud/desktop/assets/103042752/dfc5dc42-ffc6-41a3-b2e2-0e3facd9c215)

2023-07-03 17:17 UTC, jancborchardt requested changes
Nice! There is no screenshot of how it looks live with the button and additional label though right?

Cause I have 2 questions:
- Is the extra "Storage" label below necessary?
- The button says "More Memory" but shouldnt it be "More storage" for consistency? (Also note we use "Sentence case", first word capitalized only)

2023-07-04 05:50 UTC, AnkurBavisa commented
> Nice! There is no screenshot of how it looks live with the button and additional label though right?
> 
> Cause I have 2 questions:
> 
> * Is the extra "Storage" label below necessary?
> * The button says "More Memory" but shouldnt it be "More storage" for consistency? (Also note we use "Sentence case", first word capitalized only)

> Please check attached screenshots in above comment for more details and for your reference attached final output screen's screenshot.

> Yes,  "Storage" & "More Memory" widget's are required for Magentacloud only(So no "Sentence case" following)and it will be hide for Nextcloud. we are just upstream this changes for avoid code conflict in MagentaCloud side during merge.

> Just You have to look on rearrangement of "Storage Space;..." and "Progress bar" position. 
![NC_UI_Progressbar](https://github.com/nextcloud/desktop/assets/103042752/9598910c-f813-49fe-a7c3-b211cec99c4e)

2024-12-13 08:51 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-13 08:51 UTC, closed without merging