Set VFS PinState to Excluded for ignored files.
nextcloud/desktop pull request #5853
Opened 2023-07-02 17:19 UTC by m7913d

Setting PinState to Excluded ensures the syncing icon is not shown for ignored items. 
If the PinState is not set to Excluded, also all parent directories are shown as being synced, which is very inconvenient for the end user as it seems that some folder are never fully synced by Nextcloud which isn't the case. 
As long as .lnk files are not converted to placeholder files, also set them to Excluded to hide the syncing icon.

Closes #5524
Closes #5594

2023-07-02 17:38 UTC, m7913d commented
1. Note that this implementation generates many warnings "Couldn't find pin state for regular non-placeholder file" when calling `VfsCfApi::pinStateLocal` inside `Folder::slotWatchedPathChanged` on non placeholder files. Not sure if this warning is relevant. Note that we could set the PinState on non placeholder files, but querying the PinState seems to fail. OneDrive seems to do the same.

2. When setting the PinState to Excluded no sync icon is shown for that file. However, on OneDrive a special 'excluded' icon is shown:
![afbeelding](https://github.com/nextcloud/desktop/assets/84547986/8de0845c-559f-4d0a-a003-e31cbc1a30b8)
I'm not sure if and how we can set such an icon too, but showing no icon is at least much better than showing the syncing icon indefinitely.

2023-07-05 18:24 UTC, m7913d commented
@mgallien Is this PR eligible to be merged? Should someone else review this PR? Please do not hesitate to contact me if you need more information or something should be changed prior to being merged.

2023-07-09 13:31 UTC, m7913d commented
Note that the "Windows Build and Test / Build" workflow fails due to external changes. PR #5874 provides a fix for this failed workflow. Please rerun the check after that PR is approved.

2023-07-09 13:51 UTC, m7913d commented
Closes #5825

2023-07-11 17:15 UTC, mgallien requested changes
thanks a lot

2023-07-11 17:15 UTC, mgallien commented on src/libsync/vfs/cfapi/vfs_cfapi.h
> +    Optional<PinState> pinStateLocal(const QString &localPath);
```suggestion
    [[nodiscard]] Optional<PinState> pinStateLocal(const QString &localPath) const;
```

2023-07-11 19:45 UTC, m7913d commented on src/libsync/vfs/cfapi/vfs_cfapi.cpp
> +Optional<PinState> VfsCfApi::pinStateLocal(const QString &localPath)
```suggestion
Optional<PinState> VfsCfApi::pinStateLocal(const QString &localPath) const
```

2023-07-11 19:45 UTC, m7913d commented on src/gui/folderwatcher.cpp
>  bool FolderWatcher::pathIsIgnored(const QString &path)
```suggestion
bool FolderWatcher::pathIsIgnored(const QString &path) const
```

2023-07-11 19:48 UTC, m7913d commented on src/gui/folder.cpp
> +bool Folder::pathIsIgnored(const QString &path)
```suggestion
bool Folder::pathIsIgnored(const QString &path) const
```

2023-07-13 11:48 UTC, mgallien requested changes

2023-07-13 11:48 UTC, mgallien commented on src/gui/folder.cpp
> +        auto pinState = _vfs->pinState(relativePath.toString());
```suggestion
        const auto pinState = _vfs->pinState(relativePath.toString());
```

2023-07-13 11:48 UTC, mgallien commented on src/gui/folder.cpp
> +        auto pinState = _vfs->pinState(relativePath.toString());
```suggestion
        const auto pinState = _vfs->pinState(relativePath.toString());
```

2023-07-13 11:48 UTC, mgallien commented on src/gui/folder.cpp
> +        qCDebug(lcFolderWatcher) << "* Ignoring file" << path;
```suggestion
        qCDebug(lcFolder) << "* Ignoring file" << path;
```

2023-07-17 07:46 UTC, mgallien commented
@m7913d could you squash your commits as I do not think it is needed to keep 3 commits ?
then I approve and make sure this is merged
thanks again for your contribution

2023-07-17 08:07 UTC, mgallien commented
/backport to stable-3.9

2023-07-17 08:40 UTC, m7913d commented
@mgallien Commits are squashed.

2023-07-17 09:36 UTC, mgallien approved these changes

2023-07-17 12:33 UTC, claucambra approved these changes

2023-07-17 12:47 UTC, m7913d commented
@mgallien @claucambra As mentioned in my second comment, this PR generates a lot of warnings "Couldn't find pin state for regular non-placeholder file". Is this ok for you? Should we remove the warning, lower the warning to a debug/info message or use another function to check if the file has a pin state?

2023-07-18 15:09 UTC, mgallien commented
> @mgallien @claucambra As mentioned in my second comment, this PR generates a lot of warnings "Couldn't find pin state for regular non-placeholder file". Is this ok for you? Should we remove the warning, lower the warning to a debug/info message or use another function to check if the file has a pin state?

@m7913d I think (but I cannot check) that this warning dates from the early stages of this code
I would go with debug level as I would not expect this warning to really be useful now
thanks for pinging us about this as I had overlooked your question

2023-07-18 22:53 UTC, mgallien commented on src/libsync/vfs/cfapi/vfs_cfapi.cpp
> +            setPinStateLocal(localPath, PinState::Excluded);
```suggestion
        if (!pinState || *pinState != PinState::Excluded) {
            setPinStateLocal(localPath, PinState::Excluded);
        }
```

2023-07-18 22:53 UTC, mgallien requested changes
see my comment
somehow missed that earlier, sorry

2023-07-20 11:44 UTC, mgallien approved these changes

2023-07-20 13:01 UTC, merged