Changes related to add folder dialogue design changes
nextcloud/desktop pull request #5865
Opened 2023-07-05 09:28 UTC by TSI-parulsharma

Changes related to add folder dialogue design changes
![Add Folder screen 1](https://github.com/nextcloud/desktop/assets/90902670/bc8bc2df-6865-4310-8292-bded06520374)
![Add folder screen2](https://github.com/nextcloud/desktop/assets/90902670/11b26ccc-afa0-43f2-b9ef-cf997b30d44f)

2023-07-05 14:55 UTC, claucambra requested changes

2023-07-05 14:55 UTC, claucambra commented on src/gui/folderwizard.cpp
> +    _ui.subHeader->setText(tr("Step 1 from 2: Local Folder"));
```suggestion
    _ui.subHeader->setText(tr("Step 1 of 2: Select a Local Folder"));
```

2023-07-05 14:55 UTC, claucambra commented on src/gui/folderwizard.cpp
> +                            "synchronized.").arg(Theme::instance()->appNameGUI()));
```suggestion
    _ui.content->setText(tr("%1 will synchronise remote contents to a local folder of your choice. Any changes you make locally will also be synchronised to the remote location.").arg(Theme::instance()->appNameGUI()));
```

2023-07-05 14:55 UTC, claucambra commented on src/gui/folderwizard.cpp
> +    _ui.subHeader->setText(tr("Step 2 from 2: Directory in your CLOUD"));
```suggestion
    _ui.subHeader->setText(tr("Step 2 from 2: Select a Remote Folder"));
```

2023-07-17 11:32 UTC, jancborchardt reviewed
@TSI-parulsharma are the screenshots the ones from after the update? Could I ask you to add both "Before" and "After" screenshots so it is easy to compare? Thank you! :)

2024-12-13 08:50 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-13 08:50 UTC, closed without merging