Add option to notify when synced folder overcomes set size limit
nextcloud/desktop pull request #5868
Opened 2023-07-06 06:49 UTC by claucambra

This expands upon the existing feature to not sync new folders larger than a set limit

Closes #5818 

![Screenshot 2023-07-05 at 23 40 28](https://github.com/nextcloud/desktop/assets/70155116/494965a0-a0be-4740-b65d-acd2ce6cbb96)

![Screenshot 2023-07-06 at 14 46 01](https://github.com/nextcloud/desktop/assets/70155116/8719b371-f3e6-4af4-b95a-d0c9df76fcf4)

2023-07-07 10:49 UTC, mgallien commented
@claucambra build is failing

2023-07-10 09:56 UTC, claucambra commented
> @claucambra build is failing

Now fixed

2023-07-17 08:32 UTC, tobiasKaminsky commented
@claucambra I gave this a test run 
- enabled above option, limit to 50Mb
- create folder on server
- added 20kb
- synced
- added 54Mb
--> file was downloaded without problems

It is shown here:
![image](https://github.com/nextcloud/desktop/assets/5836855/184a535d-dc96-433b-bc7c-b09d7e6e8143)

2023-07-17 08:41 UTC, claucambra commented
> @claucambra I gave this a test run
> 
>     * enabled above option, limit to 50Mb
> 
>     * create folder on server
> 
>     * added 20kb
> 
>     * synced
> 
>     * added 54Mb
>       --> file was downloaded without problems
> 
> 
> It is shown here: ![image](https://user-images.githubusercontent.com/5836855/253889537-184a535d-dc96-433b-bc7c-b09d7e6e8143.png)

Great, working as expected then :) did you get the notification?

2023-07-17 09:24 UTC, tobiasKaminsky commented
No, no notification.
And it should not sync folder, but first ask what to do, like in your first screenshot:
- client notices folder about limit
- client pauses sync for now
- client asks user what to do
- "keep syncing" -> resume sync 
- "stop syncing" -> remove folder locally

2023-07-17 09:27 UTC, mgallien requested changes
@claucambra please add automated tests covering teh changes in libsync code (mainly `SyncEngine` and related classes

2023-07-17 12:36 UTC, claucambra commented
> No, no notification. And it should not sync folder, but first ask what to do, like in your first screenshot:
> 
>     * client notices folder about limit
> 
>     * client pauses sync for now
> 
>     * client asks user what to do
> 
>     * "keep syncing" -> resume sync
> 
>     * "stop syncing" -> remove folder locally

As far as I understood the task is to *warn* the user, not stop syncing the folder/stop the current sync run -- I imagine this would be annoying if sync suddenly stopped when folders grow, no?

Could you also send client logs for the sync run to debug the lack of a notification? Thanks!

2023-07-20 04:54 UTC, tobiasKaminsky commented
As the other options are also stated "ask for confirmation" I think we should do the same here.
I am sorry that I was not clear enough when writing description.

Once you have changed it, I can re-test and send debug archive if needed.

2023-07-24 07:54 UTC, claucambra commented
> As the other options are also stated "ask for confirmation" I think we should do the same here. I am sorry that I was not clear enough when writing description.
> 
> Once you have changed it, I can re-test and send debug archive if needed.

I have added an additional checkbox to disable synchronisation of files that have overcome limit now, feel free to test :)

2023-08-02 07:28 UTC, tobiasKaminsky commented
Works great!
Ready for merge :-)

2023-08-03 06:18 UTC, claucambra commented on src/gui/folder.cpp
> +    const auto normalisedPath = QDir::fromNativeSeparators(path);
not a typo ;)

2023-08-03 06:19 UTC, claucambra commented on src/libsync/discoveryphase.cpp
> +        const auto sanitisedPath = Utility::trailingSlashPath(path);
not a typo ;)

2023-08-03 07:15 UTC, claucambra commented on src/gui/folder.cpp
> +            tr("The folder %1 has surpassed the set folder size limit of %2MB.").arg(folderPath, QString::number(ConfigFile().newBigFolderSizeLimit().second));
done

2023-08-03 07:15 UTC, claucambra commented on src/gui/tray/activitylistmodel.cpp
> +    } else if (action._verb == "WHITELIST_FOLDER" && !activity._file.isEmpty()) { // _folder == folder alias/name, _file == folder/file path
done

2023-08-03 07:23 UTC, claucambra commented on src/gui/folder.cpp
> +            tr("The folder %1 has surpassed the set folder size limit of %2MB.").arg(folderPath, QString::number(ConfigFile().newBigFolderSizeLimit().second));
Actually no, this generates a warning about losing precising as arg converts to int -- will retain `QString::number`

2023-08-03 07:26 UTC, claucambra commented on src/gui/folder.cpp
> +        const auto messageInstruction =
Done now

2023-08-03 07:35 UTC, claucambra commented on src/gui/folderman.cpp
> +    folder->blacklistPath(relPath);
Done now

2023-08-04 09:34 UTC, allexzander approved these changes

2023-08-04 10:29 UTC, merged