Disable share view completely when server does not support/has disabled file sharing
nextcloud/desktop pull request #5885
Opened 2023-07-13 04:44 UTC by claucambra

Fixes #5826

2023-07-17 08:06 UTC, mgallien commented
/backport to stable-3.9

2023-07-17 09:21 UTC, mgallien reviewed
@claucambra see my comment

2023-07-18 08:29 UTC, mgallien requested changes
DCO check is failed
@claucambra please have a look

2023-07-18 08:41 UTC, claucambra commented on src/gui/filedetails/filedetails.cpp
> +    Q_ASSERT(folder);
Ok, replaced with a if check and return

2023-07-18 09:19 UTC, mgallien approved these changes

2023-07-18 13:58 UTC, merged