Rewrite share expiration date field's date handling
nextcloud/desktop pull request #5961
Opened 2023-08-08 10:07 UTC by claucambra

Rather than deal with messy dates and times (and timezones) using JS dates in QML, this PR moves the inner workings of the date input field into a C++ class using QDates, fixing lots of issues on this front.

2023-08-08 10:16 UTC, claucambra commented
/backport to stable-3.9

2023-09-06 06:09 UTC, claucambra commented
/backport to stable-3.10

2023-09-07 10:21 UTC, mgallien requested changes
we need automated tests for `DateFieldBackend` otherwise, it is complicated to predict the behavior

2023-09-12 17:02 UTC, claucambra commented
> we need automated tests for `DateFieldBackend` otherwise, it is complicated to predict the behavior

Added automated tests now

2023-09-12 17:07 UTC, claucambra commented on src/gui/filedetails/NCInputDateField.qml
> +    property DateFieldBackend backend: DateFieldBackend {
Now treated as private property

2023-09-13 08:14 UTC, mgallien approved these changes

2023-09-13 08:44 UTC, merged

2023-09-13 08:46 UTC, claucambra commented
/backport to stable-3.10

2023-09-13 11:45 UTC, krwi commented
Thank you so much, @claucambra and @mgallien! ❤️