Remove file from bulk upload black list only when upload succeeded.
nextcloud/desktop pull request #5998
Opened 2023-08-22 18:47 UTC by camilasan

*) first try to upload a batch with the current size
*) 504 errors would divide the current batch size by a factor of 2
*) all errors still put the small files in the blacklist for bulk upload

- [x] On error put item on blacklist
   - [x] Schedule another sync with smaller batch
   - [ ] Do another discovery  (?)
   - [x] if sync succeeds, remove from the blacklist
   - [x] if error again, cancel sync

2023-09-29 09:02 UTC, claucambra approved these changes

2023-10-11 09:05 UTC, mgallien requested changes
can you try adding an automated test for the new behavior ?

2023-10-11 09:05 UTC, mgallien commented on src/libsync/bulkpropagatorjob.cpp
> +    qCDebug(lcBulkPropagatorJob) << "There was an error, sync again with bulk upload batch size cut to half!";
```suggestion
    qCInfo(lcBulkPropagatorJob) << "There was an error, sync again with bulk upload batch size cut to half!";
```

2025-02-11 10:54 UTC, mgallien requested changes
new automated test seems to be broken
@camilasan can you have a look ?

2025-02-20 10:28 UTC, mgallien approved these changes

2025-02-20 10:36 UTC, merged