Fix visual bug with folder size confirmation combo box in general set…
nextcloud/desktop pull request #6035
Opened 2023-09-07 07:06 UTC by claucambra

…tings

2023-09-07 07:09 UTC, claucambra commented
/backport to stable-3.10

2023-09-07 10:29 UTC, mgallien requested changes
can you also post a screenshot of the state before your patch ?

2023-09-08 02:32 UTC, claucambra commented
> can you also post a screenshot of the state before your patch ?

Yes, of course, here's what it looks like before the fix (notice the text clipping the spin box)

<img width="677" alt="Screenshot 2023-09-08 at 10 30 10" src="https://github.com/nextcloud/desktop/assets/70155116/5c8d1c64-8ede-4e00-8011-d71c469259eb">

2023-09-11 16:36 UTC, mgallien approved these changes

2023-09-11 17:07 UTC, merged