Fix. Bulk upload. Accumulate sent bytes. Fix negative value in UI.
nextcloud/desktop pull request #6227
Opened 2023-11-16 14:38 UTC by allexzander

Fix for #5519

2023-11-19 16:38 UTC, claucambra approved these changes

2023-11-20 08:54 UTC, mgallien requested changes

2023-11-20 08:54 UTC, mgallien commented on src/libsync/bulkpropagatorjob.h
> +    std::atomic<qint64> _sentTotal = 0;
are you sure this is needed ?
do we really access `_sentTotal` from multiple threads ?

2023-11-20 16:02 UTC, merged

2023-11-20 16:03 UTC, allexzander commented
/backport to stable-3.10

2023-11-21 07:48 UTC, mgallien commented
/backport to stable-3.10

2023-12-01 15:33 UTC, allexzander commented
/backport to stable-3.10