GUI/LIBSYNC: force login flow V2 with config setting
nextcloud/desktop pull request #6261
Opened 2023-12-06 09:05 UTC by mickenordin

This patch allows a user to set the config variable:

forceLoginV2=true

This will make the client use the browser login flow instead of the webview. This is useful for making the user experience equal on Windows, Linux and Mac. Currently only Macs use the v2 flow and it was only possible to get this behaviour in the Windows and Linux clients at build time using a CMAKE flag.

The default behaviour is kept the same, and nothing changes for the user unless the flag is manually set in the config file. A setter is included in this patch, although it is not yet used in the GUI.

2023-12-06 14:05 UTC, claucambra requested changes
Lots of little formatting changes requested but otherwise looks good!

2023-12-06 14:05 UTC, claucambra commented on src/gui/wizard/owncloudwizard.cpp
> +      connect(_webViewPage, &WebViewPage::connectToOCUrl, this, &OwncloudWizard::connectToOCUrl);
```suggestion
    if (!useFlow2()) {
        connect(_webViewPage, &WebViewPage::connectToOCUrl, this, &OwncloudWizard::connectToOCUrl);
    }
```

2023-12-06 14:05 UTC, claucambra commented on src/gui/wizard/owncloudwizard.cpp
> +          _webViewPage->setConnected();
```suggestion
        if (!this->useFlow2()) {
            _webViewPage->setConnected();
        }
```

2023-12-06 14:05 UTC, claucambra commented on src/gui/wizard/owncloudwizard.cpp
> +        }
```suggestion
        if(this->useFlow2()) {
            _credentialsPage = _flow2CredsPage;
        } else {
            _credentialsPage = _webViewPage;
        }
```

2023-12-06 14:05 UTC, claucambra commented on src/gui/wizard/owncloudwizard.h
> +    bool useFlow2() { return _useFlow2; };
Please move this above with the other methods and implement within the `.cpp` file

2023-12-06 14:05 UTC, claucambra commented on src/libsync/configfile.cpp
> +
```suggestion
bool ConfigFile::forceLoginV2() const
{
    return getValue(forceLoginV2C, QString(), false).toBool();
}

void ConfigFile::setForceLoginV2(bool isChecked)
{
    setValue(forceLoginV2C, isChecked);
}

```

2023-12-06 14:05 UTC, claucambra commented on src/libsync/networkjobs.cpp
> +
```suggestion
```

2023-12-06 14:05 UTC, claucambra commented on src/libsync/networkjobs.cpp
> +  useFlow2 = ConfigFile().forceLoginV2();
```suggestion
    useFlow2 = ConfigFile().forceLoginV2();
```

2023-12-06 14:05 UTC, claucambra commented on src/libsync/networkjobs.cpp
> +                      }
```suggestion
                        if(!this->useFlow2) {
                            _resultOldFlow = WebViewFlow;
                        } else {
                            qCWarning(lcDetermineAuthTypeJob) << "Server only supports flow1, but this client was configured to only use flow2";
                        }
```

2023-12-06 14:05 UTC, claucambra commented on src/libsync/networkjobs.cpp
> +          result = LoginFlowV2;
```suggestion
        if (useFlow2) {
            result = LoginFlowV2;
        }
```

2023-12-07 02:35 UTC, claucambra reviewed
I just noticed, coud you remove the merge commits in this PR? After that we can merge :)

2023-12-07 16:16 UTC, claucambra commented
> > I just noticed, coud you remove the merge commits in this PR? After that we can merge :)
> 
> Is that how you want it? I did ` git rebase -i 369296d6ed33989fa8380e594424de2fa3b564bb` @claucambra Now I think the history is good :)

Indeed, looks good!

2023-12-08 12:53 UTC, mickenordin commented
Seems some required tests are failing for unrelated reasons, can they be restarted @claucambra ?

2024-01-19 09:27 UTC, mgallien commented
@mickenordin I am confused on the state of the PR as visible in the github web UI
could you rebase it on top of latest master and I try to merge it ?
I have no idea why no tests ran and do not see a button to rebase myself
I would have expected some explanations from github web UI

2024-01-19 09:29 UTC, mickenordin commented
> @mickenordin I am confused on the state of the PR as visible in the github web UI could you rebase it on top of latest master and I try to merge it ? I have no idea why no tests ran and do not see a button to rebase myself I would have expected some explanations from github web UI

Done!

2024-01-19 09:44 UTC, mgallien commented
so this time I had the button to enable the run of checks
I will keep an eye
thanks for the rebase

2024-01-19 09:45 UTC, mgallien commented
@mickenordin you did a merge of master instead of a rebase
please remove the merge commit ?

2024-01-19 09:59 UTC, mickenordin commented
I hate computers... I'll see if I can clean up this mess.

2024-01-19 10:11 UTC, mickenordin commented
Ok @mgallien , how is that?

2024-01-19 10:13 UTC, mgallien commented
@mickenordin perfectly fine
thanks for the work
I approved the run of the tests (except drone that is disabled https://github.com/nextcloud/desktop/pull/6363)

2024-01-19 10:37 UTC, merged