added option for High DPI displays to enable and disable scaling
nextcloud/desktop pull request #6274
Opened 2023-12-09 11:17 UTC by yjeanrenaud

https://github.com/nextcloud/desktop/issues/5373  
So I added a checkbox to the settings and the corresponding code to handle that Qt function 

Signed-off-by: Yves Jeanrenaud <yves.jeanrenaud@gmail.com>

2023-12-15 16:33 UTC, claucambra requested changes
A couple of comments :)

2023-12-15 16:33 UTC, claucambra commented on src/libsync/configfile.cpp
> +        ;
```suggestion
        false;
#endif
```

2023-12-15 16:33 UTC, claucambra commented on src/libsync/configfile.cpp
> +    //TODO need to check for platform windows:dpiawareness
Please implement this TODO

2023-12-15 16:33 UTC, claucambra commented on src/gui/main.cpp
> +    if(_configFile->scaleForHighDPIDisplay->scale == true) {
```suggestion
    if (_configFile->scaleForHighDPIDisplay->scale) {
```

2023-12-15 16:33 UTC, claucambra commented
Could you also add a screenshot of the settings window with your changes?

2024-03-04 18:32 UTC, alphasixtyfive commented
Would love to see it merged

2024-09-05 08:50 UTC, Julfried commented
Any update on merging this?

2024-12-20 15:09 UTC, Rello commented
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

2024-12-20 15:09 UTC, closed without merging