Rewrite communication between client and File Provider extensions using XPC
nextcloud/desktop pull request #6324
Opened 2024-01-02 09:15 UTC by claucambra

Makes communicating with the extensions far more ergonomic and is a requirement for #5693

Closes #6235

2024-02-07 10:02 UTC, mgallien requested changes
@claucambra can you fix the conflicts ?

2024-02-07 10:09 UTC, claucambra commented
Conflicts now fixed

2024-02-19 11:29 UTC, claucambra reviewed
Just re-reviewed this and it looks good to me @mgallien

2024-02-19 14:21 UTC, mgallien approved these changes

2024-02-19 14:40 UTC, merged