Bugfix/autostart
nextcloud/desktop pull request #6342
Opened 2024-01-09 16:30 UTC by camilasan

2024-01-10 05:55 UTC, claucambra reviewed
Looks good, only one insignificant nitpick

2024-01-10 05:55 UTC, claucambra commented on src/common/utility_mac.mm
> +    QDir plistDir = QFileInfo(QString::fromNSString(plistFile)).dir();
```suggestion
    const auto plistDir = QFileInfo(QString::fromNSString(plistFile)).dir();
```

2024-01-22 10:17 UTC, mgallien requested changes
build fail if we define `TOKEN_AUTH_ONLY` cmake option to `ON`

2024-01-22 10:17 UTC, mgallien commented on src/common/utility_unix.cpp
> +#ifndef TOKEN_AUTH_ONLY
I think you should remove this
if `TOKEN_AUTH_ONLY` is defined, the build would most probably fail ?

2024-01-22 10:17 UTC, mgallien commented on src/common/utility_win.cpp
> +#ifndef TOKEN_AUTH_ONLY
I think you should remove this
if `TOKEN_AUTH_ONLY` is defined, the build would most probably fail ?

2024-01-22 10:17 UTC, mgallien commented on src/common/utility_mac.mm
> +#ifndef TOKEN_AUTH_ONLY
I think you should remove this
if `TOKEN_AUTH_ONLY` is defined, the build would most probably fail ?

2024-01-22 10:17 UTC, mgallien commented on src/gui/generalsettings.cpp
> +    const auto theme = Theme::instance();
why not move the declaration of `theme` before the `if` line ?
you would then be able to also use it in the `if`

2024-01-22 10:19 UTC, mgallien commented
> build fail if we define `TOKEN_AUTH_ONLY` cmake option to `ON`

that said, `master` branch compilation is also broken if we define `TOKEN_AUTH_ONLY` to `ON` when configuring the build with `cmake`
meaning, I would not use this macro in modified/new code given the brokenness

2024-01-22 10:52 UTC, mgallien approved these changes

2024-01-22 10:52 UTC, merged