Add a configuration interface for macOS File Provider virtual files
nextcloud/desktop pull request #6351
Opened 2024-01-15 09:32 UTC by claucambra

**THIS DEPENDS ON #6324**

Closes #5693

This PR adds a configuration GUI for the File Provider sync engine. This UI is embedded within the traditional settings window. On desktop client configurations where file provider is not available or is disabled (i.e. on other OSes, old macOS versions) there are no new visible differences in the settings dialog.

Features:

- Check sync status
- Check storage use from materialised (hydrated) files
- Evict local copies via a dialog (requires some additional changes to make reliably)
- Signal the file provider domain (i.e. force a new sync check)
- Create a debug archive for the file provider extension

<img width="699" alt="Screenshot 2024-01-15 at 17 27 44" src="https://github.com/nextcloud/desktop/assets/70155116/23080bd5-2c1b-404b-a7e9-eaf61664c5ce">

2024-02-06 08:49 UTC, mgallien approved these changes

2024-02-07 10:01 UTC, mgallien requested changes
@claucambra  can you fix the conflicts and clean the history ?

2024-02-19 11:48 UTC, claucambra reviewed
Just re-reviewed this and it looks good to me @mgallien we can merge after #6324

2024-02-19 14:20 UTC, mgallien approved these changes

2024-02-19 14:46 UTC, merged