Use 'FindMimeFromData' from Win API instead of QMimeDatabase() functions to get the mimetype. Prevents freeze from VFS placeholders.
nextcloud/desktop pull request #6458
Opened 2024-02-17 20:07 UTC by allexzander

Similar, to how we had an issue with `.lnk` files (https://doc.qt.io/qt-6/qfileinfo.html#symbolic-links-and-shortcuts) on Windows with VFS mode on, we now have a freeze when trying to get mime-type for a non-hydrated(online-only) file in CaseClash conflict resolution dialog. This PR switches to using a Windows API-specific function to get the mime-type (same result as with QMimeDatabase() but without causing a freeze on placeholder files).

2024-02-17 20:16 UTC, allexzander commented
/backport to stable-3.12

2024-02-20 08:56 UTC, mgallien requested changes

2024-02-20 08:56 UTC, mgallien commented on src/gui/caseclashfilenamedialog.cpp
> +    const auto mime = Utility::mimeTypeForFile(_filePath);
why not ?
```suggestion
    const auto mime = QMimeDatabase().mimeTypeForFile(_filePath, QMimeDatabase::MatchExtension);
```

2024-02-22 00:06 UTC, allexzander commented
@mgallien it works, fixed, also, the other change is needed, because we end up having paths with double '/'

2024-02-22 09:17 UTC, mgallien approved these changes

2024-02-22 11:37 UTC, merged