Bugfix/expandable folder status model
nextcloud/desktop pull request #6490
Opened 2024-02-26 12:50 UTC by claucambra

Two things in this PR:

1. Code cleanup in general across `FolderStatusModel`
2. Fetch the first level of folders from root, fixing "fake" expandable folders

Fixes following bug:

https://github.com/nextcloud/desktop/assets/70155116/2c1868be-3c12-4982-a072-ec8d666746c8

2024-03-03 10:06 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +                auto add = !info->hasLabel();
Thanks, changed

2024-03-03 10:07 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +    if (!parent->isVisible()) {
Good catch, now is checked

2024-03-03 10:07 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +        auto error = reply->error();
Good point, I've removed it

2024-03-03 10:07 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +            return {folder->path() + subfolderInfo._path};
Yup, it's a nicer way to do it here; changed

2024-03-03 10:08 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +    if (!index.isValid() || (role == Qt::EditRole))
I've now added braces for all the if statements in the class

2024-03-03 10:08 UTC, claucambra commented on src/gui/folderstatusmodel.cpp
> +        auto ret = Qt::ItemNeverHasChildren;
Thanks, fixed

2024-03-03 10:45 UTC, allexzander requested changes
Great. Kindly, fix the CI compile error and squash whatever makes sense (at least review comment fixes into one).

2024-03-03 18:22 UTC, claucambra commented
> Great. Kindly, fix the CI compile error and squash whatever makes sense (at least review comment fixes into one).

Thanks, fixed the CI error and squashed some commits

2024-03-03 19:01 UTC, allexzander approved these changes

2024-03-04 10:05 UTC, claucambra commented
/backport to stable-3.12

2024-03-05 03:50 UTC, merged