Feature/macos legacy
nextcloud/desktop pull request #6498
Opened 2024-02-29 10:57 UTC by camilasan

Trying to build mac OS legacy versions from master.

2024-02-29 18:44 UTC, allexzander commented
lgtm, does it compile on the build machine? I would have @claucambra here anyways for an expert look

2024-03-03 18:28 UTC, claucambra requested changes
I think the pbxproj changes should be reverted or amended, but everything else looks great :)

2024-03-03 18:28 UTC, claucambra commented on shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
> -				MACOSX_DEPLOYMENT_TARGET = 11.0;
This breaks our Xcode integration

2024-03-03 18:28 UTC, claucambra commented on shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
> -				MACOSX_DEPLOYMENT_TARGET = 11.0;
Same goes for the other removals of the deployment targets in the pbxproj

2024-03-04 10:04 UTC, claucambra commented on shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
> -				MACOSX_DEPLOYMENT_TARGET = 11.0;
I don't think we can, but then again I don't think we need to, this doesn't affect the build we run via CMake (the deployment target on the xcodebuild run in the shell integration CMakeFiles is set by CMake). This is mainly for the IDE integration. I think we should set 11.0 as the deployment target for the File Provider extension and whatever our intended minimum target is for the Finder Sync Extension (10.13 or 10.14)

2024-03-08 09:15 UTC, tobiasKaminsky commented
Can we then backport this to 3.12?

2024-03-11 14:17 UTC, tobiasKaminsky approved these changes

2024-03-11 14:20 UTC, merged

2024-04-22 10:21 UTC, labor4 commented
Much love from me for this effort! Thanks