use a longer maximum timeout during chunk uploads
nextcloud/desktop pull request #6513
Opened 2024-03-06 10:26 UTC by mgallien

Close #5394

2024-03-29 15:16 UTC, claucambra approved these changes

2024-05-17 08:13 UTC, claucambra requested changes
@mgallien I am guessing we still want this? Unfortunately has merge conflicts now

2024-11-19 13:10 UTC, mgallien commented
> @mgallien I am guessing we still want this? Unfortunately has merge conflicts now

there is also the issue that we had problems with our timeout handling code when moving to Qt6
so this cannot be merged right now
moving to the next milestone

2024-11-29 13:05 UTC, mgallien commented
this is needed but blocked by a regression with timeout in master branch
let's keep it open for some time before we would close it if there is no progress on timeout hnalding

2025-10-06 09:27 UTC, mgallien commented
close it for now
unsure how to achieve proper timeouts

2025-10-06 09:27 UTC, closed without merging