E2EE. Fix root metadata fetching path for non-root remote sync folder. Refactoring. Stabilizing paths.
nextcloud/desktop pull request #6529
Opened 2024-03-10 13:08 UTC by allexzander

2024-03-10 13:09 UTC, allexzander commented
Yes. Again, lots of similar changes for dealing with non-root remote sync root paths. Due to the new way of fetching metadata (keys are stored in the root folder's metadata). Extensive manual tests were successful. What we are really missing is end-to-end testing. Otherwise, we are going to continue fixing regressions.

2024-03-10 13:20 UTC, allexzander commented
/backport to stable-3.12

2024-03-12 09:05 UTC, mgallien requested changes

2024-03-12 09:05 UTC, mgallien commented on src/libsync/vfs/cfapi/hydrationjob.h
> +
please remove the extra spaces

2024-03-12 09:11 UTC, mgallien requested changes
please add automated tests for such cases
would be needed to ensure this code can become more reliable

2024-03-12 20:46 UTC, allexzander commented
> please add automated tests for such cases would be needed to ensure this code can become more reliable

How do you propose to implement these tests? The e2e-to-end encryption interaction between client and server is way too complicated to implement unit tests for it. This requires writing most of the endpoints the server is using for E2EE, not just simple PROPFIND. We do not have framework for such testing for this reason.

This type of tests require different testing approach, called end-to-end testing (or QA automation), for which, we do not have capacity.

2024-03-19 21:45 UTC, mgallien approved these changes

2024-03-20 00:07 UTC, merged