if desktop client sent a first reply: wait for the menu data
nextcloud/desktop pull request #6553
Opened 2024-03-19 08:41 UTC by mgallien

may need the user to wait a bit longer but should prevent missing the context menu

should still be robust since we only wait indefinitely if desktop client sent a first reply

2024-03-19 18:30 UTC, allexzander requested changes

2024-03-19 18:30 UTC, allexzander commented on shell_integration/windows/NCContextMenu/NCClientInterface.cpp
> +    bool receivedReplayFromDesktopClient = false;
a typo `receivedReplayFromDesktopClient` -> `receivedReplyFromDesktopClient`

2024-03-20 08:44 UTC, mgallien commented on shell_integration/windows/NCContextMenu/NCClientInterface.cpp
> +    bool receivedReplayFromDesktopClient = false;
done

2024-03-20 08:46 UTC, allexzander approved these changes

2024-03-20 08:46 UTC, mgallien commented
/backport to stable-3.12

2024-03-20 08:49 UTC, merged