Feature/office files lock newly created. Plus refactoring.
nextcloud/desktop pull request #6613
Opened 2024-04-06 12:38 UTC by allexzander

2024-04-11 09:31 UTC, mgallien requested changes
seems like I cannot get it to work
![image](https://github.com/nextcloud/desktop/assets/168967/70f1253f-cbd1-4d40-9a3e-ad58a3cebf70)

2024-04-11 22:46 UTC, allexzander commented
@mgallien Should be fixed now, kindly test with new build.

2024-04-12 09:09 UTC, mgallien approved these changes
works

2024-04-13 13:58 UTC, merged

2024-04-13 13:58 UTC, allexzander commented
/backport to stable-3.12

2024-04-13 13:58 UTC, allexzander commented
/backport to stable-3.13

2024-04-13 13:59 UTC, allexzander commented
/backport to stable-3.12