Add daily update channel.
nextcloud/desktop pull request #6658
Opened 2024-04-22 16:10 UTC by camilasan

Client updater: https://github.com/nextcloud/client_updater_server/pull/144
Infrastructure: https://github.com/nextcloud-gmbh/internal-infrastructure/pull/416

- Adds the daily and enterprise option to the update url:
channel=daily

- Changes the message box test when the user switches update channels:
    - before:
    ![update-channel-before](https://github.com/nextcloud/desktop/assets/241266/41019c99-c1cc-4aab-b782-87073ee8d300)
    - after:
    ![update-channel-after](https://github.com/nextcloud/desktop/assets/241266/cf84f2bc-0f68-43e4-8a30-d35870f1ccff)

- Test:
    - [x] Linux
    - [x] mac OS
    - [ ] Windows
 - [x] ⚠️ The updater site backend part needs to be implement

2024-06-03 21:42 UTC, nimishavijay requested changes
Definitely an improvement! :) Love the bullet points, they make things so much more clear. The wording is also way more concise!
I would suggest only a few minor changes

```
- stable: contains tested versions considered reliable
- beta: contains versions with new features that may not be tested thoroughly
- daily: contains versions created daily only for testing and development

Downgrading versions is not possible immediately: changing from beta to stable means waiting for the new stable version.

```

As a follow up, I would propose some more changes:
- [x] on the settings page, the channels could be in radio buttons instead of in a dropdown.
- [ ] that way we could move the channel info directly onto the settings page
- [x] change the confirmation dialog to show only the "downgrading is not possible" message
- [ ] show the confirmation dialog only when changing from daily to beta or beta to stable 

What do you think :)

2024-06-04 16:21 UTC, Mika-6-9 commented
It's a really good idea, why only tests on Linux?
We can test on Windows if you need testers.

How will the enterprise (stable) versions be validated?

2024-06-28 07:07 UTC, nimishavijay commented
@camilasan looks great! I would only recommend that it's in a vertical arrangement instead of horizontal :)

2024-07-03 13:46 UTC, mgallien requested changes

2024-07-03 13:46 UTC, mgallien commented on src/gui/generalsettings.cpp
>          return QStringLiteral("stable");
would be more readable if everything is in the same switch statement
not sure you need a fallback value after the switch

2024-07-03 13:46 UTC, mgallien commented on src/gui/generalsettings.cpp
> +    const auto *ocupdater = qobject_cast<OCUpdater *>(updater);
```suggestion
    const auto ocupdater = qobject_cast<OCUpdater *>(updater);
```
while reading this line, everybody should be aware that is a pointer, no need to repeat the information twice

2024-07-03 13:46 UTC, mgallien commented on src/gui/updater/updater.cpp
> +    query.addQueryItem(QLatin1String("updatesegment"), QString::number(config.updateSegment()));
this is no longer in use
maybe you could remove it at the same time ?

2024-07-03 13:46 UTC, mgallien commented on src/libsync/configfile.cpp
>  }
to enable RVO (return value optimization)
please use a single return variable
```
QString ConfigFile::currentUpdateChannel() const
{
    auto updateChannel = defaultUpdateChannel();
    QSettings settings(configFile(), QSettings::IniFormat);
    if (const auto configUpdateChannel = settings.value(QLatin1String(updateChannelC), updateChannel).toString();
        validUpdateChannels().contains(configUpdateChannel)) {
        qCWarning(lcConfigFile()) << "Config file has a valid update channel:" << configUpdateChannel;
        updateChannel = configUpdateChannel;
    }

    return updateChannel;
}

2024-07-03 21:07 UTC, merged