Bugfix nextcloudcmd when syncing results in deleting all files
nextcloud/desktop pull request #6773
Opened 2024-05-21 19:33 UTC by camilasan

- Fix for https://github.com/nextcloud/desktop/issues/3144
- Makes warning more concise:
  - warning when deleting all files in the server
    - before: 
    ![Screenshot 2024-06-04 at 20 06 29](https://github.com/nextcloud/desktop/assets/241266/4fb3abec-7815-4713-9dda-935e94bf555c)
    - after:
    ![Screenshot 2024-06-04 at 20 18 01](https://github.com/nextcloud/desktop/assets/241266/fb8d8a15-cbd0-4e22-b34d-af0e9d5da566)

  - warning when deleting all local files
    - before: 
    ![Screenshot 2024-06-04 at 20 06 29](https://github.com/nextcloud/desktop/assets/241266/9c3432cb-986d-4d8d-904a-f36cbf3fd57d)
    - after:
    ![Screenshot 2024-06-04 at 20 19 54](https://github.com/nextcloud/desktop/assets/241266/1070bf52-f411-4178-bb6c-b3ccb32b8a12)

2024-06-04 22:52 UTC, nimishavijay requested changes
Super nice! Very concise and clear as well! 
I would suggest using "Proceed to remove all files" instead :)

2024-06-05 15:19 UTC, mgallien requested changes
I tested the code as it is without having ever manually modified the setting `promptDeleteAllFiles`
so default value (`false`) kicks in and we get no popup in `nextcloud` graphical full sync client and `cmd`lightweight client is not getting stuck
if you change the value to `true` I get the improved popup in the graphical client but the command line one will get stuck again

2024-06-26 06:10 UTC, claucambra reviewed
A couple of small comments

2024-06-26 06:10 UTC, claucambra commented on src/libsync/syncoptions.h
> +    bool _isCmd;
```suggestion
    bool _isCmd = false;
```

2024-06-26 06:10 UTC, claucambra commented on src/libsync/syncengine.cpp
> +        const auto guard = new QObject();
I have the same concern, did I miss something?

2024-06-28 16:16 UTC, mgallien approved these changes

2024-06-28 16:19 UTC, merged