Fix "The host name did not match any of the valid hosts for this certificate" notification even when the certificate was valid
nextcloud/desktop pull request #6785
Opened 2024-05-30 15:34 UTC by camilasan

- I am trying to solve this: the client was complaining about invalid certificates even though the certificate was valid with
"The host name did not match any of the valid hosts for this certificate"
- I only could reproduce what was reported with stable-3.13 and Qt 5 on Linux.
- We might have hit a Qt5 bug, but I couldn't find reports. 
- The issue was gone once the setting of ssl options were removed in https://github.com/nextcloud/desktop/commit/52996774b588b3bba9d99d9d18a3e7c41a421a33.

2024-05-31 09:02 UTC, mgallien reviewed
see my inline comments

2024-05-31 09:02 UTC, mgallien commented on src/libsync/networkjobs.cpp
> -    setFollowRedirects(false);
I would say that this change is wrong
from a guess on the class name, it seems we wanted to check if a redirect would happen or not
so having Qt follow redirects automatically may be wrong here
that said, I guess I am missing the context of the `CheckRedirectCostFreeUrlJob` class
if that was supposed to be able to detect network login portal then we should ensure we do not break this

2024-05-31 09:02 UTC, mgallien commented on src/gui/accountsetupfromcommandlinejob.cpp
> -    job->setFollowRedirects(false);
did you find the code that this comment refers to ?

2024-05-31 09:02 UTC, mgallien commented on src/gui/owncloudsetupwizard.cpp
> -    job->setFollowRedirects(false);
did you find the code that this comment refers to ?

2024-06-24 09:32 UTC, mgallien requested changes
build is broken
can you make sure CI is green ?

2024-06-28 16:20 UTC, mgallien approved these changes

2024-06-28 16:22 UTC, claucambra approved these changes

2024-07-01 16:20 UTC, merged