docs: switch to sphinx_rtd_theme to match other docs
nextcloud/desktop pull request #6854
Opened 2024-06-28 15:36 UTC by joshtrichards

This switches the Desktop Client Manual to the same theme used for all of our other documentation (i.e. Admin, User, Dev):

- sphinx-rtd-theme + optional dark mode 
- unifies some misc related elements ([directly copied](https://github.com/nextcloud/documentation/tree/master/_shared_assets/static) from our other documentation):
  - custom.css
  - up-to-date logos
- adds a `requirements.txt` for ease of installation of dependencies for documentation developers/contributors (this is how we do things for the other docs already)
  - e.g. `pip install -r requirements.txt`
- also includes a couple tiny bug fixes:
  - a table issue in the *Advanced Usage* chapter that broke the inclusion of the `[General]` section of the *Configuration File* section at some point in the last release or so
    - i.e. compare [current live for 3.13](https://docs.nextcloud.com/desktop/3.13/advancedusage.html#configuration-file) to [current live for 3.11](https://docs.nextcloud.com/desktop/3.11/advancedusage.html#configuration-file)
  - corrects a couple build time heading length mismatch warnings

**Notes:** 

- I think there is an additional step (automated? manual?) in the build->deploy to production for the Desktop docs. That may need some finessing since as best as I can tell there are some other bits added outside the Sphinx build process for the production deploys that are ending up on https://docs.nextcloud.com/desktop/VERSION (the outdated Nextcloud heading/etc). Presumably those are no longer needed after this change (we don't use them for the other docs at least).
- This should also make it easier to transition the docs out of the Desktop repo and over to the main documentation repo at a later date/in a follow-up if needed.

![image](https://github.com/nextcloud/desktop/assets/1731941/ed6e1885-9d25-41f4-ac30-a4fddd55d5ad)

2024-08-07 10:55 UTC, mgallien requested changes
the doc building CI check via drone is failing
can you have a look or tell us if you would need help ?
I fear we currently use an old docker image when compared to server documentation

2024-08-20 13:18 UTC, mgallien commented
@joshtrichards I am sorry for the delay
this is complicated as the build infrastructure for desktop files client is really outdated compared to the server one
I unfortunately have not much time I can allocate to this
Still it would be vert cool and valuable to merge this PR
do you feel trying yourself ?
just look at the drone "Documentation" check

2025-01-27 14:51 UTC, Rello commented
Hello @joshtrichards 

I wanted to get back to you regarding this PR. Thank you for that.
We want to take the shortcut and not even switch the theme anymore. We will directly copy the content over to the Nextcloud docs into https://docs.nextcloud.com/server/latest/user_manual/en/desktop/index.html one after the other.

during this we will also split user/developer sections were applicable.

I hope its ok for you, if we do not merge this PR anymore. your content-suggestions will be taken over...

2025-01-31 07:27 UTC, closed without merging

2025-01-31 07:27 UTC, Rello commented
Hello,

the documentation was moved to 
https://docs.nextcloud.com/#desktop
https://github.com/nextcloud/documentation

the section in this repo will be removed.

thank you for your support and your initial efforts for this PR