Only check for leading/trailing space for files on Windows.
nextcloud/desktop pull request #6871
Opened 2024-07-01 15:44 UTC by camilasan

Fix for #6807.

2024-07-09 13:58 UTC, mgallien requested changes
can you see how automated tests could be modified to validate your changes ?

2024-07-29 09:01 UTC, claucambra approved these changes

2024-09-05 09:30 UTC, tobiasKaminsky commented
/backport to stable-3.14

2024-09-26 14:30 UTC, mgallien requested changes
see my comments

2024-09-26 14:30 UTC, mgallien commented on test/testsyncvirtualfiles.cpp
> +        }
```suggestion
#if defined Q_OS_WINDOWS
            QCOMPARE(completeSpy.findItem(fileWithSpaces1)->_status, SyncFileItem::Status::FileNameInvalid);
            QCOMPARE(completeSpy.findItem(fileWithSpaces2)->_status, SyncFileItem::Status::FileNameInvalid);
            QCOMPARE(completeSpy.findItem(fileWithSpaces3)->_status, SyncFileItem::Status::FileNameInvalid);
            QCOMPARE(completeSpy.findItem(fileWithSpaces4)->_status, SyncFileItem::Status::FileNameInvalid);
            QCOMPARE(completeSpy.findItem(fileWithSpaces5)->_status, SyncFileItem::Status::FileNameInvalid);
            QCOMPARE(completeSpy.findItem(fileWithSpaces6)->_status, SyncFileItem::Status::FileNameInvalid);
#else
            QCOMPARE(completeSpy.findItem(fileWithSpaces1)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces2)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces3)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces4)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces5)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces6)->_status, SyncFileItem::Status::Success);
#endif
```

2024-09-26 14:30 UTC, mgallien commented on test/testsyncvirtualfiles.cpp
> +        }
```suggestion
#if defined Q_OS_WINDOWS
            QCOMPARE(completeSpy.findItem(fileWithSpaces1)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces2)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces3)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces4)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces5)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces6)->_status, SyncFileItem::Status::Success);
#else
            QCOMPARE(completeSpy.findItem(fileWithSpaces1)->_status, SyncFileItem::Status::NoStatus);
            QCOMPARE(completeSpy.findItem(fileWithSpaces2)->_status, SyncFileItem::Status::NoStatus);
            QCOMPARE(completeSpy.findItem(fileWithSpaces3)->_status, SyncFileItem::Status::NoStatus);
            QCOMPARE(completeSpy.findItem(fileWithSpaces4)->_status, SyncFileItem::Status::NoStatus);
            QCOMPARE(completeSpy.findItem(fileWithSpaces5)->_status, SyncFileItem::Status::NoStatus);
            QCOMPARE(completeSpy.findItem(fileWithSpaces6)->_status, SyncFileItem::Status::NoStatus);
#endif
```

2024-09-26 14:30 UTC, mgallien commented on test/testlocaldiscovery.cpp
> +        }
```suggestion
#if defined Q_OS_WINDOWS
            // no file with spaces on Windows
            QVERIFY(!fakeFolder.currentRemoteState().find(fileWithSpaces));
#else
            //Linux/Mac OS allows spaces
            QVERIFY(fakeFolder.currentRemoteState().find(fileWithSpaces));
#endif
```

2024-09-26 14:30 UTC, mgallien commented on test/testlocaldiscovery.cpp
> +        }
```suggestion
#if !defined Q_OS_WINDOWS
            QCOMPARE(completeSpy.findItem(fileWithSpaces1)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces2)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(fileWithSpaces3)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(folderWithSpaces1)->_status, SyncFileItem::Status::Success);
            QCOMPARE(completeSpy.findItem(folderWithSpaces2)->_status, SyncFileItem::Status::Success);
            QVERIFY(fakeFolder.remoteModifier().find(fileWithSpaces1));
            QVERIFY(fakeFolder.remoteModifier().find(fileWithSpaces2));
            QVERIFY(fakeFolder.remoteModifier().find(fileWithSpaces3));
            QVERIFY(fakeFolder.remoteModifier().find(folderWithSpaces1));
            QVERIFY(fakeFolder.remoteModifier().find(folderWithSpaces2));
#endif
```

2024-09-26 14:30 UTC, mgallien commented on test/testlocaldiscovery.cpp
> +#ifdef Q_OS_WINDOWS
```suggestion
#if defined Q_OS_WINDOWS
```

2024-09-26 14:30 UTC, mgallien commented on test/testlocaldiscovery.cpp
> +#ifdef Q_OS_WINDOWS
```suggestion
#if defined Q_OS_WINDOWS
```

2024-09-27 07:06 UTC, mgallien approved these changes

2024-09-27 07:26 UTC, merged

2024-09-27 08:22 UTC, mgallien commented
/backport to stable-3.12