Bugfix/delete read only remnants folders
nextcloud/desktop pull request #7061
Opened 2024-09-02 13:02 UTC by mgallien

2024-09-03 07:43 UTC, mgallien commented
popup asking for delete confirmation
![Screenshot 2024-09-03 094212](https://github.com/user-attachments/assets/4d6a9952-127a-4f6a-958b-6844acd2ee5f)

2024-09-03 07:43 UTC, mgallien commented
@nextcloud/designers can you help with the UI review ? :pray:

2024-09-05 08:29 UTC, marcoambrosini commented
@mgallien you mean review of this popup dialog? Are those windows standard components?

2024-09-05 16:31 UTC, mgallien commented
> @mgallien you mean review of this popup dialog? Are those windows standard components?

yes the popup screenshot would show the message
the components are standard ones and should follow the platform style (or way to show this type of popup)

@marcoambrosini  I am more concerned by the content of the message and if you have suggestions about it

2024-09-06 08:35 UTC, marcoambrosini commented
Got it @mgallien, I have to admit I don't understand exactly what's going on there. Could you explain the context with a bit more detail so that I can help with the text? :)

2024-09-09 14:25 UTC, mgallien commented
/backport to stable-3.14

2024-09-09 14:26 UTC, mgallien commented
/backport to stable-3.13

2024-09-09 14:29 UTC, mgallien commented
> Got it @mgallien, I have to admit I don't understand exactly what's going on there. Could you explain the context with a bit more detail so that I can help with the text? :)

@marcoambrosini
we had a bug were desktop client could leave folders that are read-only inside a read-only parent folder
those folders should have been deleted
we now detect them and ask the user confirmation before cleaning them up
not cleaning them is causing synchronization errors so the user would probably care and look at the dialog when it pops up

2024-09-11 07:46 UTC, claucambra requested changes

2024-09-11 07:46 UTC, claucambra commented on src/libsync/filesystem.cpp
> +            const auto parentPermissionsHandler = FileSystem::FilePermissionsRestore{parentFolderPath, FileSystem::FolderPermissions::ReadWrite};
This should be wrapped in the macOS related ifdefs to not break building for legacy macOS systems

2024-09-11 07:46 UTC, claucambra commented on src/libsync/filesystem.cpp
> +        FileSystem::setFolderPermissions(path, FileSystem::FolderPermissions::ReadWrite);
This should be wrapped in the macOS related ifdefs to not break building for legacy macOS systems

2024-09-11 07:46 UTC, claucambra commented on src/gui/folder.cpp
> +                                  msg.arg(listOfFolders.join("\n")), QMessageBox::NoButton);
I know that for us this makes sense but my feeling is that a normal user will have absolutely no idea what this information means, I think we may need to provide a better explanation of what the issue is and why cleaning up is a good idea

2024-09-11 09:12 UTC, jancborchardt commented
> we now detect them and ask the user confirmation before cleaning them up
> not cleaning them is causing synchronization errors so the user would probably care and look at the dialog when it pops up

@mgallien @claucambra @camilasan in these cases we should automatically clear it up. Reading this popup I only see possible confusion, and no reason to not click the "Remove remnant folders" button.

We need to do as many things as possible automatically. Every time we ask people something, it can:
- Be missed
- Be misunderstood
- Lead to confusion
- Lead to frustration why it’s not understandable
- etc.

2024-09-11 09:12 UTC, jancborchardt requested changes
> we now detect them and ask the user confirmation before cleaning them up
> not cleaning them is causing synchronization errors so the user would probably care and look at the dialog when it pops up

@mgallien @claucambra @camilasan in these cases we should automatically clear it up. Reading this popup I only see possible confusion, and no reason to not click the "Remove remnant folders" button.

We need to do as many things as possible automatically. Every time we ask people something, it can:
- Be missed
- Be misunderstood
- Lead to confusion
- Lead to frustration why it’s not understandable
- etc.

(Similar thing with the "spaces at end of filenames" issue for example.)

2024-09-11 12:54 UTC, marcoambrosini commented
> not cleaning them is causing synchronization errors so the user would probably care and look at the dialog when it pops up

Do you think we can perform this action without asking once we detect that folders that should have been deleted are in fact still there? cc @jancborchardt

2024-09-11 15:35 UTC, mgallien commented
@jancborchardt 
I agree with your points
I initially added this as I received feedback from some users that were worried about the delete operation
I will remove the dialog and indeed make sure the client is doing its best to ensure a working state with synchronization be in a working state

2024-09-11 20:17 UTC, jancborchardt approved these changes
If there is no dialog, all good from my side. :) Thanks @mgallien!

2024-09-12 07:17 UTC, claucambra approved these changes

2024-09-12 07:42 UTC, merged