Fix native UI
nextcloud/desktop pull request #7101
Opened 2024-09-11 13:47 UTC by camilasan

Continues  #7077.

............................................................
### ⚠️ TODO:

- [ ] align text/icon in buttons
- [ ] fix talk icon in activity list

![Screenshot 2024-09-13 at 11 31 38](https://github.com/user-attachments/assets/df97aa37-af11-4e1e-aa34-827ec6d8193a)

- [ ] remove black border from around the call notification

![Screenshot 2024-09-13 at 12 29 01](https://github.com/user-attachments/assets/3a9facd5-64e1-4920-808d-dca2d0df8d55)

............................................................

## mac OS

### Dark mode:
<img width="457" alt="dark-theme-apps" src="https://github.com/user-attachments/assets/6fdf2fa6-ea2c-43f8-b356-fb87edf32112">
<img width="457" alt="dark-theme-folders" src="https://github.com/user-attachments/assets/689b03c6-2f63-42f5-8fc5-2961f23c9f0d"><br>
<img width="228" alt="dark-user-menu" src="https://github.com/user-attachments/assets/71e03db7-c743-4e2c-a4cc-084a97e1d54b"><br>
<img width="457" alt="add-files-dark" src="https://github.com/user-attachments/assets/eb6b28ec-22f4-4027-bc21-3b5e9e3836ae">

### Light mode:
<img width="457" alt="light-theme-apps" src="https://github.com/user-attachments/assets/e7fd8d53-e194-434a-8533-b80043a4accd">
<img width="457" alt="light-theme-folders" src="https://github.com/user-attachments/assets/e013356b-c272-43a5-8b6e-18d08d366aba">
<br>
<img width="228" alt="light-user-menu" src="https://github.com/user-attachments/assets/c2b03527-b0bf-487e-b5db-8b3092ced709">
<br>
<img width="457" alt="add-files-light" src="https://github.com/user-attachments/assets/9631906f-5c44-404f-85be-4b678a67e08f">

2024-09-12 13:47 UTC, marcoambrosini reviewed
Outcome of call with @camilasan 

**Now** 
- [ ] Alignment of search text
- [ ] Native height and border radius
<img width="218" alt="Screenshot 2024-09-12 at 15 40 00" src="https://github.com/user-attachments/assets/e9f607ac-c80a-44d8-b818-def5d0b1e0cb">

- [x] Header color goes away 

- [ ] Adjust status icon background

- [x] Icon of more apps https://fonts.google.com/icons?selected=Material+Symbols+Outlined:apps:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=apps&icon.size=24&icon.color=%235f6368

- [x] Dropdown menus border-radius like native ones
<img width="322" alt="Screenshot 2024-09-12 at 15 41 12" src="https://github.com/user-attachments/assets/314be3da-d4f2-4b5a-9195-52623f5c35e3">

- [x] Wider account selection dropdown 150%

- [x] Folder menu: border should be as the apps dropdown and no separation lines between elements

**Possibly follow up**
- [ ] Drop-down: same margin on all of them so that they dont "touch" the boundaries of the container element
- [ ] "..." menus need to have some right margin so that they don't touch the boundaries of parent

2024-09-12 20:42 UTC, mgallien reviewed
1 small comment

2024-09-12 20:42 UTC, mgallien commented on src/gui/tray/activitylistmodel.cpp
> +                return colorIconPath.arg("activity.svg");;
there is a duplicated `;`
```suggestion
                return colorIconPath.arg("activity.svg");
```

2024-09-13 09:40 UTC, mgallien commented
/backport to stable-3.14

2024-09-13 10:32 UTC, mgallien requested changes
2 very small comments

2024-09-13 10:32 UTC, mgallien commented on src/gui/tray/activitylistmodel.cpp
> +                return colorIconPath.arg("state-error.svg");;
```suggestion
                return colorIconPath.arg("state-error.svg");
```

2024-09-13 10:32 UTC, mgallien commented on src/gui/tray/activitylistmodel.cpp
> +                return colorIconPath.arg("state-warning.svg");;
```suggestion
                return colorIconPath.arg("state-warning.svg");
```

2024-09-13 11:40 UTC, mgallien approved these changes

2024-09-13 11:40 UTC, merged