changing default chunk size to 100MB
nextcloud/desktop pull request #7161
Opened 2024-09-19 10:25 UTC by mgallien

goal is to have better perfromance and uniformize between all files clients

2024-09-19 10:41 UTC, provokateurin requested changes
Should use correct notation and size, we use that internally in server as well.

2024-09-19 10:41 UTC, provokateurin commented on src/libsync/configfile.cpp
> +    return settings.value(QLatin1String(chunkSizeC), 100LL * 1000LL * 1000LL).toLongLong(); // 100MB
```suggestion
    return settings.value(QLatin1String(chunkSizeC), 100LL * 1024LL * 1024LL).toLongLong(); // 100MiB
```

2024-09-19 10:41 UTC, provokateurin commented on src/libsync/syncoptions.h
> +    qint64 _initialChunkSize = 100LL * 1000LL * 1000LL; // 100MB
```suggestion
    qint64 _initialChunkSize = 100LL * 1024LL * 1024LL; // 100MiB
```

2024-09-24 08:55 UTC, mgallien commented on src/libsync/configfile.cpp
> +    return settings.value(QLatin1String(chunkSizeC), 100LL * 1000LL * 1000LL).toLongLong(); // 100MB
done

2024-09-24 08:55 UTC, mgallien commented on src/libsync/syncoptions.h
> +    qint64 _initialChunkSize = 100LL * 1000LL * 1000LL; // 100MB
done

2024-09-24 09:04 UTC, provokateurin approved these changes

2024-09-24 09:05 UTC, provokateurin commented
https://github.com/nextcloud/server/issues/47682 just linking for reference :)

2024-09-24 12:57 UTC, claucambra approved these changes

2024-09-26 09:52 UTC, merged