Bugfix update channels
nextcloud/desktop pull request #7350
Opened 2024-10-17 14:38 UTC by camilasan

I was just hoping to catch the issue of reports about it - like the channel changing without the user interaction.

2024-10-17 14:42 UTC, claucambra reviewed
Some nitpicks otherwise looks good imo

2024-10-17 14:42 UTC, claucambra commented on src/gui/generalsettings.cpp
> +        _ui->updateChannel->setCurrentIndex(currentUpdateChannelIndex != -1? currentUpdateChannelIndex : 0);
nit: spacing

```suggestion
        _ui->updateChannel->setCurrentIndex(currentUpdateChannelIndex != -1 ? currentUpdateChannelIndex : 0);
```

2024-10-17 14:42 UTC, claucambra commented on src/gui/settingsdialog.cpp
> +    foreach(auto account, AccountManager::instance()->accounts()) {
Better to use a ranged for loop here

```suggestion
    for(const auto account : std::as_const(AccountManager::instance()->accounts())) {
```

2024-10-31 11:23 UTC, mgallien requested changes
when built with `BUILD_UPDATER=OFF`, build failed as expected from my inline comment

2024-10-31 13:07 UTC, mgallien approved these changes

2024-10-31 13:29 UTC, merged