use new in Qt6.8 windows fluent style
nextcloud/desktop pull request #7416
Opened 2024-10-25 10:32 UTC by mgallien

2024-10-25 10:32 UTC, claucambra approved these changes

2024-10-25 10:58 UTC, mgallien commented
![image](https://github.com/user-attachments/assets/ba26833d-9883-4e36-8009-431f3cb74b50)

2024-10-25 10:59 UTC, mgallien commented
![image](https://github.com/user-attachments/assets/9d40cbed-a0ad-41e9-9ccf-1c10d51630ab)
on windows 11 with dark mode

2024-10-28 06:29 UTC, claucambra commented
/backport to stable-3.14

2024-11-11 09:04 UTC, claucambra requested changes
We need to check for the Qt version being at least 6.8

2024-12-04 08:02 UTC, mgallien commented
for people wanting to test, here is a build of this branch https://cloud.nextcloud.com/s/oT8mypQmQn9gPDc
keep it for testing only please

2024-12-04 08:07 UTC, mgallien commented
there are a couple of small issues
see
![image](https://github.com/user-attachments/assets/995d0029-aad3-4fb9-b9cb-6c776f6c4a6a)

2025-01-02 09:09 UTC, Rello commented
@nilsding

2025-01-03 10:27 UTC, nilsding commented
@mgallien the transparency in light mode is gone now:

![Screenshot_20250103_111247](https://github.com/user-attachments/assets/28f62a96-11db-4e48-8fd1-8eb97417d0c1)

I also tried to make the background have some extra blur (like you'd see in the background of the start menu), but I couldn't get it to work right with the `Rectangle` border :/  maybe something to revisit later.

2025-01-15 10:56 UTC, nilsding approved these changes

2025-01-24 09:51 UTC, ivaradi commented
> @ivaradi I am not sure if had seen that we are going to merge this very soon in master branch and the next release will require at least Qt 6.8.0

Well, the current stable version requires 6.7.0, so it is already being patched for almost all distributions (even Oracular contains only Qt 6.6). So I have started to work on providing a few extra packages containing Qt 6.8.0 and the required KDE Frameworks libraries, installing the files under /opt to avoid any clash with the existing Qt packages. 

Another way would be to recompile the newer versions of the Qt and KDE Frameworks packages for these older distributions, but there is a large number of them, and I am not sure what problems it would cause for the other Qt-based applications or on KDE-based systems. 

So it is perhaps better to provide Qt 6.8.0 in an isolated manner, though I am not sure what advantage the native packages have over the AppImage version then... Maybe only the file manager plugins.

2025-01-24 10:10 UTC, mgallien commented
> > @ivaradi I am not sure if had seen that we are going to merge this very soon in master branch and the next release will require at least Qt 6.8.0
> 
> Well, the current stable version requires 6.7.0, so it is already being patched for almost all distributions (even Oracular contains only Qt 6.6). So I have started to work on providing a few extra packages containing Qt 6.8.0 and the required KDE Frameworks libraries, installing the files under /opt to avoid any clash with the existing Qt packages.
> 
> Another way would be to recompile the newer versions of the Qt and KDE Frameworks packages for these older distributions, but there is a large number of them, and I am not sure what problems it would cause for the other Qt-based applications or on KDE-based systems.
> 
> So it is perhaps better to provide Qt 6.8.0 in an isolated manner, though I am not sure what advantage the native packages have over the AppImage version then... Maybe only the file manager plugins.

I am very sorry if you feel like we do not care.
This is really the opposite and I think your packages are being used and valued by many people including some of my colleagues.
We did not wanted to have different Qt minimum required versions on different platforms. I feel like it would be fine to patch this in your packaging work. We only really need it on Windows for the new Windows 11 style

2025-01-24 10:28 UTC, ivaradi commented
> > > @ivaradi I am not sure if had seen that we are going to merge this very soon in master branch and the next release will require at least Qt 6.8.0
> > 
> > 
> > Well, the current stable version requires 6.7.0, so it is already being patched for almost all distributions (even Oracular contains only Qt 6.6). So I have started to work on providing a few extra packages containing Qt 6.8.0 and the required KDE Frameworks libraries, installing the files under /opt to avoid any clash with the existing Qt packages.
> > Another way would be to recompile the newer versions of the Qt and KDE Frameworks packages for these older distributions, but there is a large number of them, and I am not sure what problems it would cause for the other Qt-based applications or on KDE-based systems.
> > So it is perhaps better to provide Qt 6.8.0 in an isolated manner, though I am not sure what advantage the native packages have over the AppImage version then... Maybe only the file manager plugins.
> 
> I am very sorry if you feel like we do not care. This is really the opposite and I think your packages are being used and valued by many people including some of my colleagues. We did not wanted to have different Qt minimum required versions on different platforms. I feel like it would be fine to patch this in your packaging work. We only really need it on Windows for the new Windows 11 style
> 
> Your packages provide a much better integration with the user's system including app menu and files explorer integration. We are currently unable to provide this with the AppImage. This is something that we find very valuable and I cannot say thank you enough for your contributions. I know that finding time to contribute is not something easy and I would really want to say thank you again

Thank you for appreciating my work, I did not mean to imply that I feel you do not care. I assume you have your reasons for requiring a certain minimum version of Qt. 

However, the patches are not simply about changing the required Qt version in the CMakeLists.txt file, but some parts of the code, that are used under Linux, also use newer APIs that are not present in the earlier versions (Jammy has Qt 6.2, Noble has Qt 6.4), and I am not even sure some of the fixes I made, even if they compile, really work as they should (I am a software developer, but not much familiar with Qt.), though no one seems to complain about them. This is why I thought having a recent version of Qt to build with instead of having to maintain the patches is easier. 

That said, I think it would be the best if you could ensure that the code compiles with earlier versions of Qt6 as well, at the price of certain, possibly rather special features not being available with earlier Qt versions. I know that in some instances it may require #ifdef's, which is not really elegant, though maybe with some conditional template programming this could be avoided.

2025-01-26 10:51 UTC, claucambra commented on src/gui/main.cpp
> +    style = QStringLiteral("FluentWinUI3");
Maybe we want to limit this to Windows 11+ only?

2025-01-26 10:53 UTC, claucambra commented on src/gui/main.cpp
> +    style = QStringLiteral("FluentWinUI3");
For Windows 10 we can use https://doc.qt.io/qt-6/qtquickcontrols-universal.html

2025-01-27 09:48 UTC, claucambra approved these changes

2025-01-27 10:02 UTC, merged