Bundle macOS File Provider module logs into main debug archive
nextcloud/desktop pull request #7464
Opened 2024-11-05 08:33 UTC by claucambra

Removes need for users to create the debug logs separately for macOS VFS

2024-11-19 12:55 UTC, mgallien requested changes

2024-11-19 12:55 UTC, mgallien commented on src/gui/generalsettings.cpp
> +#include "macOS/fileprovider.h"
why not ?
```suggestion
#ifdef BUILD_FILE_PROVIDER_MODULE
#include "macOS/fileprovider.h"
#endif
```

2024-11-20 02:28 UTC, claucambra commented on src/gui/generalsettings.cpp
> +#include "macOS/fileprovider.h"
Thanks, done

2024-11-22 09:08 UTC, mgallien approved these changes

2024-11-22 09:08 UTC, merged