UI: Improves texts displayed to the user when picking the wrong location for syncing
nextcloud/desktop pull request #7596
Opened 2024-12-02 21:24 UTC by camilasan

⚠️ It depends on #7636 ⚠️ 

#### Improves texts displayed to the user when picking the wrong location for syncing:

- User has no permissions to write to local folder:

![noperms](https://github.com/user-attachments/assets/d7f8674b-aee6-4357-8e85-446b529aa246)

- The sync folder in the network:

![network-location](https://github.com/user-attachments/assets/6c2a88f0-277e-4f18-9d47-3792dc03a10c)

- Local folder does not exist:

![doesnotexist](https://github.com/user-attachments/assets/83897e83-79a1-40bd-8956-c1a873dbef22)

- Trying to sync to the same folder locally:

![double-sync](https://github.com/user-attachments/assets/b9f9ef1d-aca0-4ec6-b65a-1986109ced12)

- Folder contained in sync folder:

![contained](https://github.com/user-attachments/assets/54ba2756-14b7-4029-83f8-a96d6432332e)

- Network drive/root:

![drive2](https://github.com/user-attachments/assets/ee9222df-7a23-4fa4-8610-1a2c2ddfbaea)

- Folder is already syncing to:

![already-synced2](https://github.com/user-attachments/assets/d053757c-9165-4c90-adda-733b9e6e7f7b)

- Root folder is already syncing:

![root-synced](https://github.com/user-attachments/assets/1e2be810-2b0b-48bd-b669-20fe40d454b6)

2024-12-03 07:26 UTC, Rello commented on src/common/vfs.cpp
> +            return tr("The Virtual filesystem feature does not support a drive as sync root");
"The virtual file system does not support network drives"

2025-01-27 17:55 UTC, nilsding requested changes
just two nits

2025-01-27 17:55 UTC, nilsding commented on src/gui/folderwizard.cpp
> +        ret = tr("%1").arg(warnings.first());
there is no need for this `tr("%1")`, just `warnings.first()` will do fine here

2025-02-11 03:47 UTC, claucambra approved these changes

2025-02-11 08:08 UTC, merged