Fix .netrc parsing
nextcloud/desktop pull request #7698
Opened 2024-12-28 12:02 UTC by fredrik-eriksson

Fixes: #7177

It seems that the current Tokenizer-implementation splits the netrc tokens on a (string) separator of " \n\t" instead of splitting on any of the whitespace characters which leads to the issue described in #7177.

This implementation splits the content of netrc on any whitespace character using a regex instead, but should otherwise use the same strategy for parsing. I'm not very familiar with C++ (or QT) and does not completely understand the code, so although this solution seems to work for me, I would appreciate a review :slightly_smiling_face: 

Thanks!

2025-01-02 11:36 UTC, mgallien requested changes
thanks for the PR
there would still be failing tests
see
> FAIL!  : TestNetrcParser::testValidNetrc() Compared values are not the same
>   Actual   (parser.find("frob"))                                         : std::pair("\"user", "'space")
>   Expected (qMakePair(QString("user with spaces"), QString("space pwd"))): std::pair("user with spaces", "space pwd")
>   Loc: [/home/mgallien/work/nextcloud/desktop/test/testnetrcparser.cpp(60)]

I also needed to remove the `QEXPECT_FAIL` instances from `test/testnetrcparser.cpp` file
can you add those changes to the PR ?

2025-01-03 09:55 UTC, mgallien requested changes
thanks @fredrik-eriksson 
can you fix the missing signed off comment and fix my inline comment ?
apart from that, I fully agree that your change can be merged as is and is already a big improvement

2025-01-03 09:55 UTC, mgallien commented on test/testnetrcparser.cpp
> +       //QCOMPARE(parser.find("frob"), qMakePair(QString("user with spaces"), QString("space pwd")));
please use `QEXPECT_FAIL`
it is better to document the failing test and result in the same state for the automated test

2025-01-03 11:08 UTC, fredrik-eriksson commented
Thanks for the feedback, I hope I got it right this time :slightly_smiling_face:

2025-01-03 13:46 UTC, mgallien approved these changes

2025-01-03 13:47 UTC, mgallien commented
@fredrik-eriksson thanks for the very fast review cycles
my plan is to get this merged now and backported to the current stable branch for a release next week
congratulations for your contribution and many thanks for the fix

2025-01-03 15:35 UTC, merged

2025-01-03 15:35 UTC, mgallien commented
/backport to stable-3.15

2025-01-14 22:03 UTC, ncartron commented
thanks, I can confirm that after upgrading to `nextcloudclient-3.15.3` on FreeBSD 14.1, I can now successfully use nextcloudcmd along with a `~/.netrc`